### ISSUE TITLE
Custom response headers

### ISSUE THREAD

**Issue by JonasDoebertin** [Luracast/Restler#180]
As far as I know, there is no way of specifying custom headers to be send with every response. Or is there?

Also, I think it would be nice to have an option to override the default `X-Powered-By` header from `Luracast Restler vX.X.X` to something like `My API vX.X.X (Luracast Restler vX.X.X)`.

I think it is good to have the Restler branding in this header; but having an easy option to include your own project name would be really nice.

**Comment by ChrisHolcomb** [comment]
I'm trying to put my JWT Token in a Custom Header called Auth. I can put a string in a custom header called Auth but can't figure out how to add my JWT token in there on the login response.

Is this project still alive?

**Comment by thijshakkenberg** [comment]
Did you implement OAuth server from the examples for this? We are also looking into using JWT for authentication.

**Comment by ChrisHolcomb** [comment]
No. I finally got it to work, this is the steps I took.

1) copies the Jwt class from here (https://github.com/rmcdaniel/angular-codeigniter-seed/blob/master/api/application/helpers/jwt_helper.php) into a file called JWT.php.
2) Created a file called apiAuth.php with this:
<?php
use Luracast\Restler\iAuthenticate;

class apiAuth implements iAuthenticate
{
    const KEY = 'SuperSecretKey';

    function __isAllowed()
    {
        $isAuth = false;
        // Check to see if we have an Auth header if not check for an api key
        if ($_SERVER['HTTP_AUTHTOKEN'])
        {
            $authToken = $_SERVER['HTTP_AUTHTOKEN'];
            $cleanAuthToken = str_replace('Bearer ', '', $authToken);
            $token = JWT::decode($cleanAuthToken, 'MySecretJWTKey');
            $isAuth = isset($token);
        } else {
            $isAuth = isset($_GET['api_key']) && $_GET['api_key'] == apiAuth::KEY ? TRUE : FALSE;
        }
        return $isAuth;
    }

    function __getWWWAuthenticateString()
    {
        return 'Query name="api_key"';
    }
}
3) in my login method created the JWT and added it to the header:
function putUserAuthRequest($Email=null, $Password=null, $request_data=null)
    {
        $resp = $this->db->userauth_login_request($this->_validate($request_data));
        if ($resp['idUser'])
        {
            $secretKey  = $this->db->JWT_Key;
            $tokenId    = base64_encode(crypt($resp['idUser']));
            $issuedAt   = time();
            $notBefore  = $issuedAt + 10;             //Adding 10 seconds
            $expire     = $notBefore + 60;            // Adding 60 seconds
            $serverName = 'http://api.yourserver.com';

            $data = [
                'iat'  => $issuedAt,         // Issued at: time when the token was generated
                'jti'  => $tokenId,          // Json Token Id: an unique identifier for the token
                'iss'  => $serverName,       // Issuer
                'nbf'  => $notBefore,        // Not before
                'exp'  => $expire,           // Expire
                'data' => [                  // Data related to the signer user
                    'idUser'    => $resp['idUser'],     // userid from the users table
                    'idCompany' => $resp['idCompany'],  // User name
                ]
            ];

            $jwt = JWT::encode(
                $data,      //Data to be encoded in the JWT
                $secretKey, // The signing key
                'HS512'     // Algorithm used to sign the token, see https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-3
            );

            header('AuthToken: Bearer ' . $jwt);
        }
        return array('user' => $resp);
}
4) in your .htaccess add this line:  Header always set Access-Control-Expose-Headers "AuthToken"
5) in your client app on the response of the success login write the header AuthToken in to the window session storage:
                    var authToken = headers('AuthToken');
                    $window.sessionStorage.token = authToken;
Then create an authInterceptor service to take that token and put it in every http request to your server:
(function () {
    'use strict';

    App.factory('authInterceptor', authInterceptor);

    authInterceptor.$inject = ['$q', '$window', '$rootScope'];

    function authInterceptor($q, $window, $rootScope) {
        return {
            request: function (config) {
                config.headers = config.headers || {};
                if ($window.sessionStorage.token &&
                    $window.sessionStorage.token !== null &&
                    $window.sessionStorage.token !== undefined) {
                    config.headers.AuthToken = $window.sessionStorage.token;
                }
                return config;
            },
            response: function (response) {
                // Handle responses here

                return response || $q.when(repsonse);
            },
            responseError: function (response) {
                console.log('Response Error Status: ', response.status);
                if (response.status === 440) {
                    console.log('Recieved Response Status of 440, should be redirected to login...');
                    delete $window.sessionStorage.token;
                    response.headers.AuthToken = '';
                    $rootScope.userProfile = null;
                    $rootScope.$broadcast('unauthorized');
                }
                return response || $q.reject(repsonse);
            }
        };
    }

    App.config(function ($httpProvider) {
        $httpProvider.interceptors.push('authInterceptor');
    });

})();

**Comment by Arul-** [comment]
@ChrisHolcomb Thanks for contributing to Restler. Yes Restler is alive and kicking!

If you want to keep track of the progress, check the v3 branch, https://www.facebook.com/Luracast, and https://twitter.com/Luracast

**Comment by roydekleijn** [comment]
Is @ChrisHolcomb way of setting response header, the way to go ?
or is there some other way?
