### ISSUE TITLE
Restler 3.0 Feature Requests and Ideas

### ISSUE THREAD

**Issue by electrical** [Luracast/Restler#22]
Since you asked for idea's, let me start with some :-)
1. **Output structure:** http://groups.google.com/group/api-craft/browse_thread/thread/9b046e863b5943df. Metadata is something that can be generated from the API it self. Links can be generated from the class the user builds.
2. **Correct header settings:** http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html. Think some things here can be found that are useful. Like: 14.7 Allow
3. **Pagination:** limiting the returning result set. Can be build in the api class of the user self, but perhaps some core functionality can be build in the API core ?
4.  **JsonP**: JsonP as part of the package; JsonP becomes more and more important with cross-domain usages.
5. **Versioning Support**: To have an inbuilt Restler way to manage your API versions (Request from @KitCarrau in issue #21)

More will follow when they pop up in my mind :-)

**Comment by cperrot** [comment]
What happened to the feature 
"Improved metadata support to enable API discovery through possible ways like WADL, Swagger UI, Google API discovery etc (@murdock - hope this answers your question)"
was that dropped or is it implemented in Version 3?
