### ISSUE TITLE
Help with Upload file

### ISSUE THREAD

**Issue by d4icon** [Luracast/Restler#241]
I need upload file.
I have looking at various threads : http://stackoverflow.com/questions/15733608/file-upload-with-restler-v3

But I need something more detailed. ¿As the calling? I user PostMan of Chrome for test.
you can give me an example?

Thanks

**Comment by RVN-BR** [comment]
Sorry for bringing this up again, is there a way to document correctly an upload parameter?

http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.param.pkg.html doesnt seem to mention anything?

**Comment by Arul-** [comment]
Once we implement swagger 2, there will be a way! for now just mark it with your comments

**Comment by RVN-BR** [comment]
@Arul- Sorry to bring this up, but is there any way to set a @param tag for an upload field?  Also, when using a POST or PUT, should regular fields be in the body and attachments?

I'm trying * @param array $files {@required false} attachments
but results arent as expected... should it be from body or not? thx

**Comment by Arul-** [comment]
are you trying to upload a single file or multiple files?

**Comment by RVN-BR** [comment]
@Arul- it should support multiple uploads preferrably...  Although it may be useful to have an option for single/multi for some uses?
