### ISSUE TITLE
Problem with swedish characters (utf8?)

### ISSUE THREAD

**Issue by rendom** [Luracast/Restler#33]
I have problem to return swedish characters. i think its a utf8 problem. When i return some data from my database its just return null if it contains any "special character".

When i pass data to the server and return it then i get outputs like this "test\u00e5\u00e4\u00f6test"

**Comment by typeguards-attainment28** [comment]
> [@kasperfn](https://github.com/kasperfn) there is no date yet, but we keep updating the progress at this [status report wiki](https://github.com/Luracast/Restler/wiki/Restler-3-Status-Report) page and discuss about various aspects of it at [#22](https://github.com/Luracast/Restler/issues/22)





https://phps.space/questions/the-php-code-showcases-the-use-of-unicode-escaped-characters
