### ISSUE TITLE
Proposals for the dependency injection container

### ISSUE THREAD

**Issue by ghost** [Luracast/Restler#330]
Hi Arul,

I noticed your Scope class (and a thread on Stackoverflow where you introduce it). While it's a great idea to enable DI in RESTler, but in fact, the current solution has some issues.
- One of them is that it's not really DI, but service location that I can see being used in RESTler (Scope::get() is invoked 50+ times and Scope is effectively a static class). The following article highlights the disadvantages of the practice of service location: http://www.devtrends.co.uk/blog/how-not-to-do-dependency-injection-the-static-or-singleton-container.
- Another problem is that it's impossible to use a third party container which could instantiate our controllers/services (am I right?). I want to use PHP-DI: beside others, a huge advantage of it that it is compliant to a PHP-FIG-like standard for DI containers (https://github.com/container-interop/container-interop).

So it would be great to change the way RESTler uses DI. My "action plan" is the following:
- First, enable the usage of external containers, so that controllers/services could be instantiated by them. In my opinion, only container-interop compliant containers should be regarded.
- Then the Scope class could support the aforementioned standard, so it would become optional to use it or not.
- Finally it could be worth refactoring RESTler to use real DI (not service location).

If you are ok with my opinion, I could make a PR soon for the first step. But the second and the third ones need more time and effort to be developed, so I don't promise anything.

**Comment by soda-2005** [comment]
> With the above commit that will soon be part of RC6 all you need is
> Scope::$resolver = function ($className) use ($context) {
>    return $context->getByType($className);
>};

I tried to use the dependency-Injection (of my MVC-framework), but it did not work in Explorer (when i want to see the online-documentation for my API's). When i call the online-documentation of my API's, than this PHP-Fatal-Error appears:
PHP Fatal error:  Call to a member function getRequestedApiVersion() on a non-object in Luracast/Restler/Explorer.php on line 167

The problem/bug is in class 'Scope' in Method 'get':
When Scope::$resolver is defined, than the 'logic' does not take place, where some object-properties were set. This PHP-code will not be called:
Scope:get:
>            if (class_exists($fullName)) {
>                $shortName = Util::getShortName($name);
>                $r = new $fullName();
>                static::$instances[$name] = (object)array('instance' => $r);
>                if ($name != 'Restler') {
>                    $r->restler = static::get('Restler');
>                    $m = Util::nestedValue($r->restler, 'apiMethodInfo', 'metadata');
>                    if ($m) {
>                        $properties = Util::nestedValue(
>                            $m, 'class', $fullName,
>                            CommentParser::$embeddedDataName
>                        ) ?: (Util::nestedValue(
>                            $m, 'class', $shortName,
>                            CommentParser::$embeddedDataName
>                        ) ?: array());
>                    } else {
>                        static::$instances[$name]->initPending = true;
>                    }
>                }
>            }
I would be very cool, when you can fix that bug, so i could really use my own dependency-Injection :-)

**Comment by soda-2005** [comment]
oh, i forgot, i use restler in version 3.0.0-RC6

**Comment by soda-2005** [comment]
I created a new Issue (#423) for that bug:
https://github.com/Luracast/Restler/issues/423
