### ISSUE TITLE
Notice array to string conversion on AutoLoader.php line 266

### ISSUE THREAD

**Issue by GregOriol** [Luracast/Restler#357]
When using Reslter and another class loader (one from Symfony here) with PHP 5.5, a php notice appears:

```
Notice: Array to string conversion in .........../vendor/luracast/restler/vendor/Luracast/Restler/AutoLoader.php on line 266
```

It seems that array_unique compares string values and not array values, and $rogueLoaders is an array of arrays.

Quick solution for me was to replace line 266 with `$loaders = static::$rogueLoaders;` (ie. removing the array_unique call) but maybe a better one could be found?

**Comment by mankms** [comment]
@GregOriol, there is a `SORT_REGULAR` option for [array_unique](http://php.net/manual/en/function.array-unique.php) function. So, you may change line 266 to:

```php
$loaders = array_unique(static::$rogueLoaders, SORT_REGULAR);
```

And it works.
