### ISSUE TITLE
Disable Cache for specific user-role?

### ISSUE THREAD

**Issue by letsbyteit** [Luracast/Restler#376]
Hey guys,
I've just a little question about the caching. I want to offer the "admin-user-role"-users always fresh data that isn't cached. (I mean the cache configured by PHPDoc-Params)
Is there any possibility to do so? Or is that only the message the browser gets "cache this request 30 seconds"?

Seems a bit stupid, I know. But would I be able to serve fresh data to authenticated users?

**Comment by Arul-** [comment]
Not sure if you are still looking for this!
