### ISSUE TITLE
Swagger 2.0

### ISSUE THREAD

**Issue by ksnyde** [Luracast/Restler#382]
Swagger 2.0 is now live. Any plans to bring that goodness over to Restler? 

> Side note: I think the current change notes could be clearer on where the 1.2 spec came into 3.x release. Also, there's still a 1.2 branch but that appears to be out of date now that 1.2 has made to the 3.x releases; I think it may make sense to remove that unless it's still serving a function.

**Comment by Arul-** [comment]
@ksnyde thanks for your suggestions, I will do them one by one!

**Comment by Arul-** [comment]
@ksnyde updated the readme of the api explorer project to let every one know about the newer version :)

**Comment by ksnyde** [comment]
Great thanks.

**Comment by RVN-BR** [comment]
Sorry guys, but how is Explorer used now?  I changed the add api class from Resources to Explorer... Should I expose the files in the explorer dir (html/css/js) to my webserver? /API/resources.json now yields 404.... /explorer.json also doesnt work?

**Comment by Arul-** [comment]
@RVN-BR just add `Explorer` as the api class and then point your browser to `/explorer`

resources.json is now under `/explorer/resources.json`

Good thing about this is, you can use the second param to change explorer to whatever you like

```php
$r->addApiClass('Explorer', 'swagger');
// now /swagger gives you the explorer interface
```

**Comment by RVN-BR** [comment]
Aha! I see, will test it now... :)  Our webserver separates static content from dynamic content, I hope this isnt too much of an issue... let me poke... :+1:  

(on another note - didnt want to open another issue as i'm not sure what to consider - was there any change in RC5>RC6 where multiple routes defined by comments are no longer supported? we seem to be considering only the first route? more on this in a bit after I get explorer going :dash: )

**Comment by Arul-** [comment]
@RVN-BR multiple manual routes should be supported

**Comment by RVN-BR** [comment]
Thanks to API explorer its now clear there is something wrong with the accept type of POST requests.... (my bad, POST was after GET on the first few failed methods I found...lol)...  I didnt find an accept config in default, its weird I'm getting Forbidden: Content type `text/plain` is not supported but only for POST requests... and no matter what response content type I select)...

As a note, HTML Response Content is breaking Explorer layout... perhaps it should be disabled?

**Comment by Arul-** [comment]
> As a note, HTML Response Content is breaking Explorer layout... perhaps it should be disabled?

@RVN-BR  Not sure! can you share more info and a screen shot?

**Comment by Arul-** [comment]
When you use POST, request body can't be blank which is the reason for xml or text content type. Make sure there is some json body all else will be fine

**Comment by RVN-BR** [comment]
Sure, I will attach normal JSON Explorer output, and "broken" HTML output... of the same method...

**Comment by RVN-BR** [comment]
About the text/html error, what do you mean json body?  This APIs receive input from regular web forms, they are supporting an existing web app, its not possible to change the input format... Are request variables no longer supported?  Is there a log somewhere of the changes of RC5->RC6? We are a bit afraid of moving RC6 into testing, then production as we arent really sure what to expect in terms of changes?

**Comment by RVN-BR** [comment]
Upon further testing I'm having different behavior and different errors based on inverting the route comment, like so:

GET /method
POST /method

and 

POST /method
GET /method

produce different requirements/errors, etc... but only on RC6.... I will revert to 5 for now as I have some ppl breathing down my neck now :( sorry I cant contribute more right now...

**Comment by ksnyde** [comment]
@RVN-BR that sounds like an odd problem considering sequence of calls shouldn't be *able* to make a difference considering Restler is stateless. I suspect there must be something stateful happening with your scripts which is causing this variation. Of course I'm sitting in a proverbial *dark room* with zero context to your details but still the pure logic of of my argument seems to make sense to me. :)

Hope that helps;  it would be great if you could come back to this thread when you've got a few cycles as it'll be very hard for anyone to reproduce this at the moment. 

@Arul- I do think @RVN-BR suggestion of an actively managed CHANGELOG.md (or similar) might be very helpful for people considering the migration process. In my experience it can be a not insignificant task to do retroactively but maybe just getting it started now we will start to have this resource as a reference document. Certainly in the formal 3.0 build it seems like a very good idea.

**Comment by RVN-BR** [comment]
Yeah... I'm also a bit in the dark as this was reported by another developer, I was able to see it happening, but I cant say what it is... I thought it was an encoding issue or accept type issue, but for some reason, I'm getting different errors on different orders of the methods, and different formats requested/sent... What I do know is that RC5 is working fine and RC6 is not, so before I can fix it it would be good to knw what changed ;)

Yes, doing a changelog retroactively is a nightmare, but the earlier it gets started the better it is... There is an overall changelog, but more detailed things arent there, and RC6 changes still arent there at all... When trying it out its very hard to debug...  We have hundreds of methods and serve a couple of apps with the API, any updates can break things we dont even imagine, even if tests are passing... a changelog would be really useful and would ease a lot migration as @ksnyde mentioned... I can second that all migration processes were a bit traumatic, and would have been eased with a changelog/migration path had one existed

all the best! I'll try and get more info when I can...
