### ISSUE TITLE
Dependency on PHP 5.4

### ISSUE THREAD

**Issue by ksnyde** [Luracast/Restler#388]
Can you either change your `composer.json` to PHP 5.4 or remove (or downgrade the version) of Illuminate as it requires PHP 5.4:

> illuminate/support/Illuminate/Support/helpers.php on line 426

**Comment by ddrager** [comment]
Also ApcCache should be removed for > 5.4 as APC was removed in 5.5 and later.

**Comment by RVN-BR** [comment]
There is still in-memory cache on php 5.4 >.  Only APC code caching was removed.

Apc object cache, as is the case for the ApcCache extension in R3 should remain.  We use it currently in testing in php 5.6.  We will move to production soon.

The extension tests for the presence of the functions which should prevent any failures. 

For anyone interested, the required extension to maintain object caching (afaik the fastest cache method for large scale apps for in-server storage) is APCU.  Its the drop-in replacement for user storage part of the depracted APC Op code cache.  http://pecl.php.net/package/APCu

**Comment by Arul-** [comment]
@ksnyde in RC6 we no longer include Illuminate by default, It is only part of the suggestion where version is not mentioned!

**Comment by ksnyde** [comment]
That's what I thought you had intended but it wasn't what I thought I was experiencing but maybe we chalk this up to an dirty composer cache? Not sure anyway I upgraded to PHP 5.5 so my problems are sort via a different route.
