### ISSUE TITLE
Getting onto v3, not tag 3.0.0

### ISSUE THREAD

**Issue by ksnyde** [Luracast/Restler#390]
I'm back in PHP-land after a vacation in JS so maybe I'm being daft but ... I can NOT seem to get composer to load branch `v3`. I tried the following in *composer.json*:

    "luracast/restler" : "dev-v3"

But composer couldn't find this branch so I instead tried just `v3` which it resolved to `3.0.0`. Finally I force-fed it:

    "luracast/restler" : "dev-master#bb95dc0cb918ce5142958b5e55c11615e48c8c86"

> note: [bb95dc0cb918ce5142958b5e55c11615e48c8c86](https://github.com/Luracast/Restler/commit/40e38ba075a63a2c6a45d7f35366429ed52464ab) is most recent commit in branch `v3`

which it accepted but I'm not sure what state I'm really in because I definitely do NOT have the new [1.2 Explorer](https://github.com/Luracast/Restler/tree/v3/vendor/Luracast/Restler/explorer) and for that matter I was cheating a bit when I asked for that commit since it's not even in the master branch yet. 

Can you help?

**Comment by b-mille** [comment]
What version do you want exactly ?
You can find help with Packagist : https://packagist.org/packages/luracast/restler
For the last v3 version, try "3.*@dev" for example.

You can download the last API explorer directly on GitHub : 
https://github.com/Luracast/Restler-API-Explorer

**Comment by Arul-** [comment]
As @b-mille correctly pointed out `"luracast/restler": "3.*@dev"` will get you the bleeding edge from the `v3` branch which includes the new Explorer class and embedded explorer assets.

@b-mille :  API Explorer in https://github.com/Luracast/Restler-API-Explorer is not the latest! Starting from `RC6` Restler comes bundled with the latest explorer, which is what @ksnyde is looking for

**Comment by b-mille** [comment]
@Arul: ROGER ! ;)

**Comment by ksnyde** [comment]
Many thanks guys. :+1:
