### ISSUE TITLE
Handle JSON data in APIClass method

### ISSUE THREAD

**Issue by fhahne** [Luracast/Restler#391]
Assuming that I have the following APIClass:

```php
class foo {
  function getJSONData(){
     // Some logic to retrieve a JSON string from a data base
    $json = loadFromDb();
    return $json;
  }
}
```
This provides the following service:
http://myServer/foo/getJSONData.json

Now I do not really want to support any other return formats than JSON for this service, so ideally I would simply return the `$json` string as is, with the HTTP headers set accordingly. Essentially I only want to use the routing part of Restler for this particular service. Is there any way to do that?

 The `$json` string can be fairly large, and the overhead of parsing it into a PHP array and feeding it to the whole Restler output format machinery is very costly.

Thanks,
Florian

**Comment by Arul-** [comment]
Here is how you can go about it

```php

<?php

use Luracast\Restler\Restler;

class Foo
{
    /** @var  Restler */
    public $restler;
    public function json()
    {
        $json = loadFromDB();
        $this->restler->composeHeaders();
        die($json);
    }
}
```

### Note :- 
 - **restler** property is injected at runtime to all api classes
 - get is a prefix to route the api method to HTTP GET so if your method is `$foo->getJsonData` resulting url will only be `htttp::/myserver/foo/jsondata`
- above example will be available in `http::/myserver/foo/json` as HTTP GET as GET is the default when no prefix is added.
