### ISSUE TITLE
Serving multiple APIs from a single server - cache namespaces

### ISSUE THREAD

**Issue by RVN-BR** [Luracast/Restler#393]
I have encountered an issue with the way restler caches its routes.  This makes it problematic to serve multiple APIs from the same server (in some cases), or single endpoint (in other cases)...

The problem is that the classes cache is always stored under a fixed cache name "routes".  When using a single endpoint directory, or a single cache directory, to be more precise, it means that multiple APIs would read the same cache and therefore not work.  (lets say I have an API for admin and one for users, and they add different classes - I chose which one to invoke based on a domain, or ip or some other variable within my endpoint, for example).  In this case it will not work.

When using APC, then the problem is even more widespread as the cache key "routes" is one for the entire server (or once per namespace at least).  One way (I guess the best/only way?) to get around this, and perhaps the most correct (to split the cache spaces), is to assign a different cache namespace (if using apc), or different cache directory (if using files) for each API.  When I tried doing that, however, it seems that the ApcCache had a bug that always overwrote the namespace with 'restler' (line 30 ApcCache.php).

I changed line 30 & 32 of ApcCache.php as below, and it seems to be working:

FROM (always forcing namespace=restler):
```php
    function __construct($namespace = 'restler')
    {
        self::$namespace = $namespace;
    }
```

TO (only change namespace if an argument is passed to constructor):
```php
    function __construct($namespace = null)
    {
        self::$namespace = $namespace ? $namespace : self::$namespace;
    }
```
NB: there is already a static declared above the constructor stating the default $namespace='restler'

  Nonetheless, it must be set by writing straight into the class static, as ApcCache doesnt have a SetProperty function like the defaults class does, and the defaults setproperty doesnt accept another class to set a default value to... (this isnt a problem per se, but not so pretty in terms of convention some would argue)...

@Arul- do you think this is correct or am I doing something wrong elsewhere?  If I'm correct then would you incorporate the above fix in ApcCache?

Another idea would be to add Cache namespace to the defaults class, or use the CacheDirectory as a "Cache Parameter" (for file cache it would be path, for APC it would be namespace, etc)... that way we can use setproperty and its more standardized...

**Comment by b-mille** [comment]
Which version are you using?

It seems that it is already solved 6 month ago with this issue : https://github.com/Luracast/Restler/issues/327

There is no constructor like that in the current version of ApcCache.php :
https://github.com/Luracast/Restler/blob/master/vendor/Luracast/Restler/ApcCache.php

**Comment by RVN-BR** [comment]
Strange, I will refresh the sources from the master again..... hopefully no breaking changes :)

sorry for the confusion anyways... the comment about adding the namespace in the defaults still stands though...
