### ISSUE TITLE
Urls with dashes are returning 404

### ISSUE THREAD

**Issue by JoyceBabu** [Luracast/Restler#394]
Urls with dashes (hyphen) are returning 404. For example, `/api/ringtone-generator.json` gives 404, whereas `/api/ringtonegenerator.json` works correctly.

I checked the generated `routes.php`, and it is showing `ringtonegenerator` irrespective of whether the actual url contains a dash or not.

The following routes.php was generated when the url was `/api/ringtone-generator.json`
http://pastebin.com/4w1Ez7Ww

    // PHP Handler code 
    $r = new Restler(true, true);
    $r->addAPIClass('Downloads\\Ringtones\\Rest\\RingtoneGenerator', null);

**Comment by JoyceBabu** [comment]
Any update on this? Thank you.

**Comment by Arul-** [comment]
Can you paste the routes.php here itself? your pastebin is no longer there!

**Comment by Arul-** [comment]
I tried url with hyphens. They seems to work fine at least in RC6. Did you try RC6?

**Comment by JoyceBabu** [comment]
I have upgraded to RC6 and retried after clearing the cached routes.php. But it is still not working.

Here is the routes.php for `/api/ringtone-generator.php'.
http://pastebin.com/96RhJZjY

**Comment by Arul-** [comment]
How are you adding the hyphen to the url? something like the following?

```php
$r = new Restler();
$r->addAPIClass(''Downloads\\Ringtones\\Rest\\RingtoneGenerator", 'ringtone-generator');
```
null is not the right value to pass for the second parameter

**Comment by JoyceBabu** [comment]
Setting the second argument worked. Thank you.
