### ISSUE TITLE
License discrepancy

### ISSUE THREAD

**Issue by stevenbalthazor** [Luracast/Restler#396]
In the Readme.md you mention that the source code is released under the LGPL; however, the License file that you are including is the GPL license not the LGPL license.  Is this intentional or an oversight?

**Comment by Arul-** [comment]
It is not intentional. Just an oversight! Will get it sorted out. Thanks for letting us know!

**Comment by Arul-** [comment]
Fixed in 43b80c108543b62076a2bf928bb10ce75041edfc
