### ISSUE TITLE
WADL support

### ISSUE THREAD

**Issue by myalban** [Luracast/Restler#397]
Does it planified ?

**Comment by RVN-BR** [comment]
Hmm.. Havent come accross anything that uses this, but you could surely implement something similar to the Swagger Resources class if you need it.

**Comment by myalban** [comment]
Finaly swagger seem to be perfect. Do you have any plan to add swagger 2.0 support ?

**Comment by RVN-BR** [comment]
@myalban apparently its on the todo... #382 ;)

**Comment by myalban** [comment]
coool

**Comment by Arul-** [comment]
Currently it's not a priority we will weigh in based on the requests and re-look at it after swagger 2.0 support
