### ISSUE TITLE
Swagger 2.x support

### ISSUE THREAD

**Issue by myalban** [Luracast/Restler#399]
Hi,

I'm planning to integrate Swagger 2.x support, does I need to start from scratch ? or it exist something ?

Thanks

**Comment by ksnyde** [comment]
1.2 is integrated currently. Look at 3.0r6 and you'll find it there I believe (the once separate API-Explorer is no longer the most recent integration). Look forward to hearing of your progress.

**Comment by Arul-** [comment]
Look in the v3 branch for `Luracast\Restler\Explorer` class that targets swagger 1.2

You can use it as the starting point to quickly build for swagger 2 spec

It is in our roadmap too but we have some pressing issues to solve before that

**Comment by anasanjaria** [comment]
I have followed [this] (https://github.com/Luracast/Restler/wiki/Restler-3:-Using-it-with-Laravel's-structure-and-Database) tutorial and want to use API Explorer so I added `$r->addAPIClass('Resources');` in index.php but it gives 500 Internal Server Error.

Also I tried to comment the line require_once '../../../vendor/restler.php'; in actual restler examples & it gives the same 500 Internal Server Error so I try to add that file ( from examples ) to existing working code but still it wont work for me ... 

I think it might be problem related to autoloading .. so can you please guide me ??

**Comment by Arul-** [comment]
@anasanjaria make sure restler is running in debug mode and look at the response, it will have clues on what went wrong!

**Comment by anasanjaria** [comment]
@Arul- it is in debugging mode .. I am using ` $r = new Restler();` in index.php

**Comment by Arul-** [comment]
@anasanjaria what is the complete response? Does that 500 internal error has a json response? if yes what is it? if no json, this could be some other issue not related to restler

**Comment by anasanjaria** [comment]
@Arul- Here is my index file that contains something like this 

`// http://stackoverflow.com/questions/25819870/unable-to-get-laravel-database-and-restler-working-with-versioning
use Luracast\Restler\Restler;
use Luracast\Restler\Defaults;

Defaults::$useUrlBasedVersioning = true;
$r = new Restler();
$r->setSupportedFormats('JsonFormat', 'XmlFormat');

$r->setAPIVersion(2);
$r->addAPIClass('Users');
//$r->addAPIClass('Luracast\\Restler\\Resources');
$r->addAPIClass('Resources');`

when I try to use explorer it hits resource.json & response is 

`{
    "error": {
        "code": 403,
        "message": "Forbidden: at least one Authentication Class is required"
    },
    "debug": {
        "source": "Restler.php:925 at authenticate stage",
        "stages": {
            "success": [
                "get",
                "route",
                "negotiate"
            ],
            "failure": [
                "authenticate",
                "message"
            ]
        }
    }
}`

**Comment by Arul-** [comment]
@anasanjaria didn't you mention a 500 error before? I'm confused.

Anyway this 403 error means that you don't have an authentication class defined and your api class has a protected method. Either make all your api as public or create and add an authentication class

**Comment by anasanjaria** [comment]
@Arul- I want to use API Explorer in [this](https://github.com/Luracast/Restler/wiki/Restler-3:-Using-it-with-Laravel's-structure-and-Database) piece of code & make necessary changes in index.php for [API Explorer] (https://github.com/Luracast/Restler/wiki/Restler-3:-API-Explorer) & added `$r->addAPIClass('Resources');` . 

When I hit resources.json at API root it throw the above mentioned json i.e 403 Forbidden .

& also all methods in my class are public.

**Comment by anasanjaria** [comment]
@Arul- Resources file is under vendor section which it automatically infer or should I have to create another resource class called MyResources class & extend it with Luracast\Restler\Resources & change discoveryUrl in swagger to that of mine ... 

Well it did work for me but the second request made by swagger was 
base/url/resources/resources.json
instead of 
base/url/resources/users.json
like the one in [here] (http://restler3.luracast.com/examples/_008_documentation/explorer/index.html#!/authors-v1)
[1st request] (http://restler3.luracast.com/examples/_008_documentation/resources.json)
[2nd request] (http://restler3.luracast.com/examples/_008_documentation/resources/authors.json)

**Comment by thijshakkenberg** [comment]
@Arul- any plans on releasing this in the near future?

**Comment by doratias** [comment]
any news about this PR?

**Comment by Arul-** [comment]
Bleeding edge of v3 branch already has swagger 2 support. Check it out
