### ISSUE TITLE
RC6 breaking change in class annotation - potential security issue for production...

### ISSUE THREAD

**Issue by RVN-BR** [Luracast/Restler#400]
I'm unsure if this is by design (I dont suppose so as this feature was introduced in RC4 and is great), but @class annotations with arrays are now broken in RC6.  I just tried changing between RC5 and RC6 to confirm.

Its ok up to RC5.  on RC6 its returning as a single parameter split with commas...

Original release note: "Support for custom class parameters and array of custom class parameters"

Syntax: * @class VendorName\Package\Class {@apiType parameter_one,parameter_two}

Return up to RC5: Array ['parameter_one','parameter_two']
Buggy in RC6: string 'parameter_one,parameter_two'

Thanks to all for the help... Found this out by chance as I've been really far behind on my restler stuff unfortunately... :(

EDIT: appears to be a bug as I see the , as a delimiter in there but for some reason its not working... I'll see if I find something...

**Comment by Arul-** [comment]
We will look into it ASAP

**Comment by RVN-BR** [comment]
Thanks... couldnt find much... I found the explode on the ',' in the comment parser on both versions... but couldnt find a lot to go on... couldnt give it too long though... thanks for the help arul! want to check some new things on new version @Arul-

**Comment by Arul-** [comment]
You can use the alternative syntax given below first

    @class VendorName\Package\ClassName ```json {"apiType": ["parameter_one","parameter_two"]}```

This will work in both RC5 and RC6

**Comment by RVN-BR** [comment]
Hi @Arul- understood, but this will require changing hundreds of functions..... :(

Will the old syntax be corrected for RC6 and beyond or will that be deprecated? (in which case I suggest removing it from the doc asap).  Please let me know if a fix will come or if we should look into changing all API definitions.  Also, is there a performance impact in the JSON syntax? (like I said we have hundreds of api methods)...

**Comment by Arul-** [comment]
Here is how to get it working in RC6.


In your index.php add the following lines

```php
use Luracast\Restler\CommentParser;

CommentParser::$allowsArrayValue['apiType'] = true;
```

This will make sure property apiType gets an array :)

**Comment by RVN-BR** [comment]
Great! Thanks! :)
