### ISSUE TITLE
OAuth2

### ISSUE THREAD

**Issue by Fanda36** [Luracast/Restler#401]
Hi,

I have problem with routing in Server.php. Problem is described in my post on Stack: http://stackoverflow.com/questions/28499226/restler-oauth2-server

Thanks.

**Comment by Fanda36** [comment]
Use routing in Stack post on "public function postAuthorize($authorize = false)" in Server.php correctly? Solution in Stack post work for me only on local server (Windows 5.5.15). On Linux PHP 5.5.21 get 404 error (but sometimes it works).

Thanks.

**Comment by Fanda36** [comment]
Can please write example to set routing on "public function postAuthorize($authorize = false)" (Server.php OAuth2 - http://restler3.luracast.com/examples/_015_oauth2_server/readme.html). 

This is not work for me on Linux (return 404) Server.php:
 /**
     * Stage 3: Client directly calls this api to exchange access token
     *
     * It can then use this access token to make calls to protected api
     *
     * @format JsonFormat,UploadFormat
     * @access public
     * @url POST apiMobile/grand
     */
    public function postGrant()
    {
        static::$server->handleTokenRequest(static::$request)->send();
        exit;
    }


init.php:

        require_once EXTERN_DIR.'/OAuth2/Autoloader.php';
        OAuth2\Autoloader::register();
        require_once EXTERN_DIR.'/vendor/restler.php';
        require_once CLASS_DIR.'/Server.php';


        $r = new Restler();


        $r->addAuthenticationClass('Auth\\Server', '');
        $r->setSupportedFormats('JsonFormat', 'XmlFormat');//, 
        $r->addAPIClass($controllerClass,'');
        $r->setOverridingFormats('JsonFormat');
        $r->setOverridingFormats('UploadFormat');
        $r->handle();

Thanks.

**Comment by Arul-** [comment]
Stale!
