### ISSUE TITLE
'string' type (in @param) validation problem

### ISSUE THREAD

**Issue by gesior** [Luracast/Restler#402]
I tried to use example API function code (tested with 3.0rc5, 3.0rc6 - master, v3):

    /**
     * Restrict the length of the string
     *
     * @param string $string {@min 2}{@max 5}
     *
     * @return string
     */
    function postString($string)
    {
        return $string;
    }

but it does not work. I found that in **Luracast\Restler\Data\Validator** in line 458 in variable **$info->type** is value **Luracast\Restler\Data\String**, so code below does not execute:

    switch ($info->type) {
    ...
    case 'string' :

I hope you can find easily where is a problem and fix it.
--
I got also a simple question: Is there any tutorial how to write own variable types [for @param] /validators?

**Comment by Arul-** [comment]
May we know your server info ( is it linux? if yes which flavour, apache or nginx, php version etc)?

**Comment by Arul-** [comment]
Quick fix is to remove the Scope::$classAliasases mapping for `String'

You can do that by using the following code in your index.php

```php

use Luracast\Restler\Scope

unset(Scope::$classAliases['String'];
```

Proper fix is being worked out! :)

**Comment by gesior** [comment]
Platform: Windows7, XAMPP, PHP 5.6.
I was looking for some PHP framework to create REST service for my angularJS website and Luracast is first framework with all features that I need for my project, but that bug.. :(
