### ISSUE TITLE
CommentParser dropping 0 from the comment

### ISSUE THREAD

**Issue by nickamon** [Luracast/Restler#404]
Hi, 

I have the following doc comment on a parameter for one of my API classes:

     * @param int $limit  the number of devices to retrieve.  Specify 0 to return all.

The API doc though, only shows the following:
"the number of devices to retrieve. Specify to return all."

The 0 is being dropped.  I looked at the code and the problem seems to arise from the following line in CommentParser 198:

```php
$value = array_filter(preg_split('/\s+/msu', $value));
```

According to the array_filter documentation, "if no callback is supplied, all entries of array equal to FALSE (see converting to boolean) will be removed."  Since the doc comment is split by a space, 0 is one of the elements, which evaluates to false and is dropped from the returned array.

**Comment by nickamon** [comment]
If the intent is to remove NULL, FALSE and Empty Strings, a comment on the array_filter function specifies that using strlen will do so and still leave 0 intact.  I have tested this solution, i.e. with the following line and it worked:

$value = array_filter(preg_split('/\s+/msu', $value), 'strlen');

**Comment by Arul-** [comment]
Thanks for reporting and the fix! we will apply it ASAP
