### ISSUE TITLE
Use of "Callable" is PHP5.4 only

### ISSUE THREAD

**Issue by polesen** [Luracast/Restler#406]
The definition of Scope::register

    public static function register($name, Callable $function, $singleton = true)
    {
        static::$registry[$name] = (object)compact('function', 'singleton');
    }

includes the "Callable" typehint. This is PHP5.4 only, hence fails with: `PHP Catchable fatal error:  Argument 2 passed to Luracast\Restler\Scope::register() must be an instance of Luracast\Restler\Callable, instance of Closure given`

On frontpage it is stated, that Restler is PHP5.3 compatible.

Wouldn't it be possible to simply remove the typehint?

**Comment by Arul-** [comment]
> Wouldn't it be possible to simply remove the typehint?

Sure! will do

**Comment by polesen** [comment]
Cool, thanks!
