### ISSUE TITLE
Could I build relative url  "products/5/galleries" in Restler 3?

### ISSUE THREAD

**Issue by pjyong** [Luracast/Restler#407]
Hi Dear Team
I have started move my own project to the good api design framework. But after I look into the document, I still can not find a way to build this url like "products/5/galleries".
The gallery is belong some product. Above url will fetch all of galleries of the product of ID=5.
Could you tell me how to finish it?
Thanks
June

**Comment by Arul-** [comment]
Read http://restler3.luracast.com/examples/_006_routing/readme.html to understand about creating custom routes

    @url GET {id}/galleries

as part of the comment in Products::getGalleries method will get you what you wanted

**Comment by pjyong** [comment]
Yes, I tried it, it works, thanks again.
