### ISSUE TITLE
Extending RC6's Explorer

### ISSUE THREAD

**Issue by ksnyde** [Luracast/Restler#408]
I have a requirement which I suspect will be a common requirement for people which is being able to brand the API Explorer to. I had done that with the old explorer by forking the API Explorer and making the HTML/JS changes I needed on the swagger side. Now that the Explorer is included in the same repo as Restler this strategy seems a bit clumsy. I'm just wondering if there is a suggested strategy for this requirement?

**Comment by Arul-** [comment]
Out of the box Explorer has some customization options under `ExplorerInfo` class

```php
use Luracast\Restler\ExplorerInfo;
ExplorerInfo::$title = "Branded Explorer";
ExplorerInfo::$contact = 'admmin@branded.com';
```

Look at the class for more properties

**Comment by ksnyde** [comment]
That's a reasonable starting point but I think most people will want to play with it a bit more than this allows.

**Comment by RVN-BR** [comment]
I think the best way looking fwd would be a custom CSS file one can set a path to and copy from a template and go from there maybe?

Although if the HTMLs, JS and CSS for swagger are static I'd much rather they not be served from within restler...  We have static asset servers and CDNs for this very purpose...  Unless all the content is really dynamic, I dont see why it needs to be coming from inside restler.

**Comment by Arul-** [comment]
Create the explorer and place your html, css and other asset files, they will be used instead. For your case just the css will do
