### ISSUE TITLE
Content-type text/plain not supported

### ISSUE THREAD

**Issue by ksnyde** [Luracast/Restler#409]
When using the new API explorer (v1.2 in RC6) I am getting an error which i didn't get with the old 1.1 API:

![image](https://cloud.githubusercontent.com/assets/980757/6374057/6d1ac6dc-bcdc-11e4-8c4b-ea3ae5cc83af.png)

I suspect there is some configuration that I was "getting away with before" but which is now being stricter in behaviour but I'm not really certain how to proceed.

**Comment by Arul-** [comment]
When you use POST, request body can't be blank which is the reason for xml or text content type. Make sure there is some json body all else will be fine. This is how swagger 1.2 behaves

**Comment by ksnyde** [comment]
I see this issue showing up in a general Swagger conversation in late 2012 / early 2013 and I think related to v1.2 of the API. 

> supportHeaderParams: true,
headers: { "Content-Type": "application/json; charset=UTF-8" },

I think this might be a better solution? Requiring content into the request's body seems a bit fragile doesn't it? Especially when Swagger's own interface doesn't meet this requirement.

**Comment by Arul-** [comment]
Now the priority for us to move to swagger 2 spec

**Comment by ksnyde** [comment]
Sure but if a one line fix fixes this I'm assuming you're fine with doing that? I'm going to put that line in and see as I can't use 1.2 as-is.

**Comment by Arul-** [comment]
Sure!

**Comment by ksnyde** [comment]
Ok. Will drop you a PR if it works.

**Comment by ksnyde** [comment]
BTW, do have an ETA for v2?

**Comment by ksnyde** [comment]
Ok on first blush that fix doesn't seem to work for the version 1.2 that we're using. Will revert to 1.1 for now and wait for v2.

**Comment by RVN-BR** [comment]
@ksnyde @Arul- just FYI this was popping up for me on my tests...  Webforms submitting to the API are all returning this error...
