### ISSUE TITLE
Authorization Regression

### ISSUE THREAD

**Issue by ksnyde** [Luracast/Restler#411]
After updating to the latest build of Restler RC6 the API explorer now exposes all API endpoint regardless if the user has authenticated. Nothing besides upgrading was done so I think this is likely a regression.

![image](https://cloud.githubusercontent.com/assets/980757/6376740/cfe754b8-bced-11e4-997d-0f0ca0fddbcc.png)

**Comment by stevenbalthazor** [comment]
I think this was caused by a missed else in vendor\Luracast\Restler\Restler.php
the last part of the authenticate method is now:
```php
    }
    $this->authenticated = true;
```
this should be:
```php
    } else {
        $this->authenticated = true;
    }
```

**Comment by ksnyde** [comment]
@stevenbalthazor nice job tracking this down. @Arul- this a pretty serious break, can we get this fixed soon?

**Comment by RVN-BR** [comment]
Yikes!! its quite serious... one more reason a detailed changelog isnt just "nice to have" it a must!

**Comment by Arul-** [comment]
@stevenbalthazor thanks :+1: 

@ksnyde & @RVN-BR,  only reason I take liberty to experiment with RC6 is, it is not public yet. When it becomes public, I will make sure it has proper change log and rest of the documentation! Of Course all your contribution to the documentation will accelerate the process :)
