### ISSUE TITLE
Api Key / Throtteling

### ISSUE THREAD

**Issue by Snoop** [Luracast/Restler#412]
Is Restler able to do throtteling like Calls / Hour / IP / API Key ?

**Comment by RVN-BR** [comment]
Yes.  You can create your own filter class for custom rate limiting, or adapt from the example.

http://restler3.luracast.com/examples/_009_rate_limiting/readme.html

rgds!

**Comment by Arul-** [comment]
Take a look at the RateLimiting class,  thats what you need
