### ISSUE TITLE
Hide documentation of one parameter in swagger-ui

### ISSUE THREAD

**Issue by gnouet** [Luracast/Restler#415]
Hi, 
Is there a way to designate a parameter of function that should not be documented, so that the parameter will not be visible in swagger-ui ?

Thank you!

**Comment by Arul-** [comment]
Currently it is not possible. Can you explain your use case?

**Comment by ksnyde** [comment]
Interestingly I had a similar requirement show up last week. In my case there was a parameter which while occasionally useful it had some performance implications and I would not want to advertise its availability broadly for fear that it's uptake would be be taken on without consideration for the trade offs.

**Comment by Arul-** [comment]
There is one easy way to make it work! if the parameter is expected in the query string.

All the method parameters will be documented in swagger so skip that from the parameters list and directly read it using `$_GET['param_name']` inside your api method

**Comment by ksnyde** [comment]
Perfect. I had forgotten about that option.

**Comment by gnouet** [comment]
It's unfortunate to have several ways to retrieve variables in the same function, but yes, it's works.
Thank you for this great project !

**Comment by Arul-** [comment]
@gnouet I'm not sure I get it! Why it is unfortunate?

**Comment by gnouet** [comment]
It's a pitty that a large part of variables is in function arguments list, and another part of variables is in the function body (using `$_GET['']`)

**Comment by Arul-** [comment]
Yes! it is not recommended. But since you need a special feature that is not supported you need use this hack!

**Comment by RVN-BR** [comment]
I disagree that the flexibility of having "hacks" is undesireable... as long as you know what you are doing and why, flexibility is always good.  It is dangerous if you have programmers which are not aware of this, and dont take care of how they do things.

It is also difficult to implement new features without breaking legacy code (which is sometimes impossible or very time consuming to re-write) without keeping "hacks" / "workarounds" open.  I'm very thankful that Restler has so far been friendly to developers who have chosen to adopt it.  It is not viable for a company to re-write their code every time a framework is updated, for example, just like its not viable for a framework to be ready for every single excption a developer might require.  Extensibility and flexibility are one of restler's strong suits!  I'm sure others who use it can attest to this.

**Comment by gnouet** [comment]
I don't say having hacks is undesirable. 
I say that in terms of maintenance, it is not ideal to have two ways to get and validate the function parameters.
What do you think of introducing a new tag like {@nodoc} ?

**Comment by ksnyde** [comment]
I don't think @gnouet was being overly negative, let's not beat him up.  :)

For my $.02, this is a feature that would be nice-to-have because it would provide a consistent mechanism for documenting your interface in its entirety (phpDocumenter, etc.) while maintaining the flexibility to expose only those attributes you want to via Swagger UI. I think there are genuine use-cases for this and while the proposed work-around meets my needs for the moment I still think it probably does qualify as a "hack" or a "less than ideal" solution for the longer term. For me at least though there is no urgency and I am glad there is a "hack" to meet immediate needs.

@Arul- keep up the awesome work. I love the product.

**Comment by RVN-BR** [comment]
Didnt mean to beat anyone up... I apologize if anyone felt beat up :)

But I remain behind my position that having flexibility is good... using it or not is up to each one of us...  And while I appreciate that a no-doc for a param might be useful, its better to have an option of implementing this and other stuff (with hacks/alternative implementations/customization of classes) than having no option except waiting for "official support"... No framework is immune from developer stupidity, so as lead developers we must impose coding standards, etc, but having a framework that doesnt *allow* flexibility is worse imo... 

Now that I think of it, wouldnt it be possible to add a custom api explorer class to support that specific doc type?

**Comment by RVN-BR** [comment]
Whipped this up in 2 minutes... dont know if its the best way or not but if you really need this, one way is to copy the Resources.php file (sorry I'm not using the Explorer yet as I couldnt upgrade to RC6 as its breaking a lot of our apis, so until its officially out with a changelog I'm on rc5 and resources) to another location and change it as follows:

Change the following code starting at line 324:

´´´php
if (isset($m['param'])) {
                    foreach ($m['param'] as $param) {
                        //combine body params as one
                        $p = $this->_parameter($param);
                        if ($p->paramType == 'body') {
                            $this->_appendToBody($p);
                        } else {
                            $operation->parameters[] = $p;
                        }
                    }
                }
´´´

add line as follows:

´´´php
if (isset($m['param'])) {
                    foreach ($m['param'] as $param) {
                        if ($param['properties']['hidedoc']) continue; // <--- if param includes {@hidedoc} annotation, hide from API Documentation.
                        //combine body params as one
                        $p = $this->_parameter($param);
                        if ($p->paramType == 'body') {
                            $this->_appendToBody($p);
                        } else {
                            $operation->parameters[] = $p;
                        }
                    }
                }
´´´

Then on your API code, add {@hidedoc} to whatever param line you want to hide, and presto :)

**Comment by Arul-** [comment]
Nice work @RVN-BR :+1:  I want to find a tag that will work on both PHPDoc and Restler!

Anything comes to mind?

**Comment by Arul-** [comment]
How about internal?

as per http://2tbsp.com/system/files/phpdoc_cheatsheet.pdf

# `{@internal}}`

     {@internal any text including inline tags}} 

Mark documentation as private, internal to the software project in text flow

**Comment by RVN-BR** [comment]
No problm, always a pleasure to contribute when I can @Arul-

In the Explorer.php class I also think I found 3 places that would need similar modification, but since afaik that is still under development, I didnt post it here... If anyone wants the code for Explorer.php I can paste it too, but didnt try it...

One small question, why does @internal have two }} ? (or is that a typo?)

**Comment by Arul-** [comment]
@RVN-BR I'm wondering the same, yet to read more about it!

**Comment by Arul-** [comment]
Unlike other inline tags, `{@internal}}` may contain other inline tags due to its purpose. To terminate an `{@internal}}` inline tag, you must use two ending brackets "}}"
Use` {@internal}}` to facilitate the creation of two sets of documentation, one for advanced developers or for internal company use, and the other for the general PHP public. Use this inline tag or its cousin, `@internal`

Reference : http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.inlineinternal.pkg.html

**Comment by Arul-** [comment]
This means, the comment parser needs an upgrade!

**Comment by RVN-BR** [comment]
It seems if I'm not mistaken that the open form of @internal may work with the current parser tho...?  Might be best to support it through that, no? @Arul- 

http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.internal.pkg.html

**Comment by Arul-** [comment]
`@internal` can hide entire api method from documentation but we need `{@internal}}` to hide a param or property

**Comment by RVN-BR** [comment]
Sorry @Arul- I must have misread...

I thought something like

@param $myparam
@internal this will be hidden {@param $hiddenparam}

would be woking...but I guess you are right...
