### ISSUE TITLE
Undefined indexes in 5.4

### ISSUE THREAD

**Issue by RVN-BR** [Luracast/Restler#416]
When doing some validation under 5.4, noticed a behaviour as follows...

\nNotice: Undefined index: $EditID in /var/www/phpPackages/luracast/restler/vendor/Luracast/Restler/Routes.php on line 242
\nNotice: Undefined index: $DetailID in /var/www/phpPackages/luracast/restler/vendor/Luracast/Restler/Routes.php on line 242

I would suggest changing line 242 in Routes.php to read:  $index = isset($call['arguments'][$match]) ? $call['arguments'][$match] : null; or something to this effect?  I'm not sure what the effect of putting a null there is... it suppressed the error but I'm not sure its the correct fix...

Warning are showing with $Varname as well as just Varname, I'm assuming these are comming from the troutes in docblocks...

rgds

**Comment by Arul-** [comment]
@RVN-BR  Can you try in RC6?

**Comment by RVN-BR** [comment]
I will give it a go on a dev container, but we were having many issues with RC6 I was afraid of putting it even on our internal dev since I didnt know what to go around to fix (remember the changellog idea, it tarted because of this difficulty... but I'll try it now and see about this specific error)

rgds!

**Comment by RVN-BR** [comment]
Just check I screwed something up.... my hp 5.4 is now 5.3 magically....grrr... let me get it back to 5.4, 5.6 or something and check again... sorry for the delays arul...

**Comment by Arul-** [comment]
I will close the issue for now, but we can continue to figure out the issue and re-open it if needed
