### ISSUE TITLE
Restler in HHVM

### ISSUE THREAD

**Issue by RVN-BR** [Luracast/Restler#417]
Has anyone run Rester in HHVM?

I'm porting a project right now... I'll post my results but was wondering if anyone has been there before me...

all the best!

**Comment by Arul-** [comment]
Haven't tried it yet! Eager to hear your results :+1:

**Comment by RVN-BR** [comment]
For now lets give you one word... encouraging :)

Finishing up some code issues with other parts of the code, nothing Restler specific for now, and then onto profiling...

**Comment by Arul-** [comment]
Keen to get an update on this :)

**Comment by RVN-BR** [comment]
I'm sorry for the delay...  Been using mostly on RC5.  Apparently it is in a working state.  I need to get more experience into profilig a real-world, non production HHVM app vs a PHP 5.3/5.4/5.6 app...

maybe others have ideas?  Spinup time for requests is DEFINITELY longer (as expected) but execution feels quicker.  Again, how much is in my code and how much in R3 is unknown at this point...

New relic has limited HHVM support but there is XHProf or similar that would run in both... I just have never set it up and with so many other stuff on my "to-do" I couldnt approach it again :(

In my experience it DID work... the improvements remain to be quantified.  Also, tests with the pre-build examples might be a better scenario than with my app.  but since I'm using containers it shouldnt be an issue to plug in the examples in order to test.  I can easily switch HHVM <> PHP on my container setup. :)

**Comment by Arul-** [comment]
I will close the issue but let us keep discussing here!
