### ISSUE TITLE
Hybrid authentication and bad credentials

### ISSUE THREAD

**Issue by HomelessGruesomeMoose** [Luracast/Restler#421]
Hi,

I'm facing with an issue with hybrid authentication. I want my resource to be partially publicly available but I also want to tell the client when their credentials are in invalid.

At the moment, if the client gives bad credentials, I throw a RestException which seems to be caught somewhere in Restler and the client gets the version of the resource which is   publicly available.
Thus, I tried throwing a custom Exception for bad credentials. Unfortunately, Restler will transform this into a 500 Error when it should be 401 and I can't choose the message.

I did find a partial workaround:

```php
$restler->addErrorClass('InvalidBasicAuthentcationException');

class InvalidBasicAuthentcationException extends \Exception {

   public function handle500() {
       throw new RestException(401, 'Invalid Basic Authentication Credentials');
   }
}
```

However, the problem is that now all 500 Exceptions are transformed into 401.

A quick hack will be to do this in Restler.class.php (1096):

```
if (!$exception instanceof RestException) {
           $exception = new RestException(
---                    500,
+++                ($exception->getCode()) ? $exception->getCode() : 500,
               $this->productionMode ? null : $exception->getMessage(),
               array(),
               $exception
           );
       }
```

Which would allow me to throw an exception with some crazy number, say 9999, to be handled specifically.

Would you have any other suggestions?
Thanks

**Comment by Arul-** [comment]
Solution is simple, you just have to keep `RestException` as your base class instead of `Exception`

**Comment by HomelessGruesomeMoose** [comment]
I thought I tried that but maybe I had other debugs working at the same time. I'll try again with more belief. Thanks.

**Comment by Arul-** [comment]
I mean whatever exception you are throwing, that should extend RestException. That should fix the issue for you

**Comment by HomelessGruesomeMoose** [comment]
Hi, I'm sorry but RestException is completely ignored. I tried debugging and got as far as seeing that $this->get() in Restter::handle() won't throw a RestException but will throw a generic Exception.

I now see where the problem lies. Restler::authenticate() has these lines:
```php
foreach ($this->authClasses as $authClass) {
                try {
                  ..............
                } catch (RestException $e) {
                    if (!$unauthorized) {
                        $unauthorized = $e;
                    }
                }
            }
            $this->authVerified = true;
            if ($unauthorized) {
                if ($accessLevel > 1) { //when it is not a hybrid api
                    throw $unauthorized;
                } else {
                    $this->authenticated = false;
                }
            } 

```
In other words, it would seem that the behaviour I am encountering is hardcoded to happen.
