### ISSUE TITLE
PHP-Fatal Error in Explorer (v3.0.0-RC6) when using own Dependency-Injection-Container

### ISSUE THREAD

**Issue by soda-2005** [Luracast/Restler#423]
When i use this configuration (to define my own dependency-Injection-container):
> $objectManager = new MyOwnDependencyInjectionContainer();
> Scope::$resolver = function ($className) use ($objectManager) {
>     return $context->get($className);
> };
> $r->addAPIClass('MyOwnApiClass');

...than the Explorer (in Version 3.0.0-RC6) ends with this PHP-Fatal-Error:
PHP Fatal error: Call to a member function getRequestedApiVersion() on a non-object in Luracast/Restler/Explorer.php on line 167

The problem/bug is in class 'Scope' in Method 'get':
When Scope::$resolver is defined, than the 'logic' does not take place, where some object-properties were set. This PHP-code will not be called:
Scope:get:
>           if (class_exists($fullName)) {
>               $shortName = Util::getShortName($name);
>               $r = new $fullName();
>               static::$instances[$name] = (object)array('instance' => $r);
>               if ($name != 'Restler') {
>                   $r->restler = static::get('Restler');
>                   $m = Util::nestedValue($r->restler, 'apiMethodInfo', 'metadata');
>                   if ($m) {
>                       $properties = Util::nestedValue(
>                           $m, 'class', $fullName,
>                           CommentParser::$embeddedDataName
>                       ) ?: (Util::nestedValue(
>                           $m, 'class', $shortName,
>                           CommentParser::$embeddedDataName
>                       ) ?: array());
>                   } else {
>                       static::$instances[$name]->initPending = true;
>                   }
>               }
>           }

It would be very cool, when you can fix that bug, so i could really use my own dependency-Injection :-)

**Comment by Arul-** [comment]
See if the above fix solves your problem!

**Comment by soda-2005** [comment]
Hi Arul,
thanks for your help, but sorry, the bugfix doesn't work :-(

This Code doesn't work:
} elseif (is_callable(static::$resolver) && $name != 'Restler') {

But, this Code works fine:
} elseif (is_callable(static::$resolver) && false === stristr($name, 'Luracast\Restler')) {
