### ISSUE TITLE
Problem with production-mode

### ISSUE THREAD

**Issue by Michaelcgn** [Luracast/Restler#425]
Hi,
i've got a problem with the production mode. 
In debug mode i get the following response:
Request: http://api.example.org/resources.json?api_key=789c7db89a852f970e9a7a005cb
Response:
```
{
    "apiVersion": "1",
    "swaggerVersion": "1.1",
    "basePath": "http://api.example.org.de",
    "produces": [
        "application/json"
    ],
    "consumes": [
        "application/json"
    ],
    "apis": [
        {
            "path": "/resources/serps_weekly.{format}",
            "description": ""
        },
        {
            "path": "/resources/serps_direct.{format}",
            "description": ""
        },
        {
            "path": "/resources/status.{format}",
            "description": ""
        }
    ]
}
```
With production-mode true (new Restler(true)) i get the following response:
```
{"apiVersion":"1","swaggerVersion":"1.1","basePath":"http:\/\/api.example.org","produces":["application\/json"],"consumes":["application\/json"],"apis":[]}
```
And the explorer show nothing :-|
Where can i look to solve the problem? 

Best,
Michael

**Comment by Michaelcgn** [comment]
With Restler(true,true) it works like expected.

Best,
Michael

**Comment by Arul-** [comment]
using RC5 with Resources class or RC6 with Explorer class?

**Comment by Michaelcgn** [comment]
Sorry, i forgot to mention it. It's the RC6? But what did you mean with Explorer Class? Is there a breaking change with the RC6?
Best,
Michael

**Comment by Arul-** [comment]
Yes, Resources class is targeting swagger 1.1 spec, where as the new Explorer class is currently targeting swagger 1.2 spec and will soon be upgraded to swagger 2 spec

**Comment by ksnyde** [comment]
Any timeframe yet for Swagger 2?

**Comment by Arul-** [comment]
@ksnyde not yet!
