### ISSUE TITLE
Explictly stating the Body's content-type

### ISSUE THREAD

**Issue by ksnyde** [Luracast/Restler#426]
I typically put JSON payloads into the Body of the message but when I just want to allow a text input I'm not sure how to achieve this as it seems to always default the content-type to `application/json`:

Using the definition:

```php
	* @param	string		$message		{@type string} {@from body}	Message being sent
````

I still get ... 

![2015-03-17_13-07-58](https://cloud.githubusercontent.com/assets/980757/6687842/a4ce2630-cca6-11e4-9031-371688dc8db8.png)

**Comment by Arul-** [comment]
With just restler, it is possible to create a format that supports mime type `text/plain` and use it to post a string as is, but not sure about the explorer support! swagger 2 may or may not cut it!
