### ISSUE TITLE
PSR-4 Autoloader

### ISSUE THREAD

**Issue by dupkey** [Luracast/Restler#430]
I've read that the PSR-4 autoloader is a nice speed improvement. Any plans to update to PSR-4 in the future?

Btw, thanks for this awesome product! Restler3 FTW.

**Comment by RVN-BR** [comment]
Its my understanding that basically the PSR-4 flattens out the folder structure a bit, but doesnt really bring a lot of difference in speed?  The main gains come, obviously, from using a classmap to cache the folder-class structure.  This is done by composer autoloader when using the -o flag, and afaik should always be used in production (its a bit slower to install/update as it generates this class map, but should be negligible in production when compared to the speed imrpovements)...  

Restler also does its class map caching, does it map the files to include, or only routes-to-classes are cached?  If this is the case, perhaps the Restler production runtime "cache compiler" should just be upgraded to include a class-file mapping?  Then composer optimized + restler in prod mode would yield best of all worlds?

I'm not sure if there is a way to leverage the composer loader to do class-mapping for restlers API classes...maybe an option? perhaps too complex and may add a dependency on using the composer autoloader when some may not be using it?
