### ISSUE TITLE
Resources.json does not show restricted api calls

### ISSUE THREAD

**Issue by thijshakkenberg** [Luracast/Restler#432]
After updating, swagger does not show the restricted api calls when entering a valid api key. We found out that the problem resides in resources.json, which does not show the restricted api calls when accessing with api_key=... in the url.

**Comment by Arul-** [comment]
I guess you have updated from RC5 to RC6 and started using the new Explorer class

Am I right?

**Comment by thijshakkenberg** [comment]
Yes, that's correct. We have reverted to RC5 as a workaround.

**Comment by Arul-** [comment]
Just fixed it with e2f0e0899d5564a3f4a99cb62d46d6328c01ea76
