### ISSUE TITLE
Optional pattern

### ISSUE THREAD

**Issue by pgh70** [Luracast/Restler#434]
I would like to validate a variable with the `@pattern` annotation, but the variable is optional (`@required false`)... Using the pattern makes is required...

My annotation:

    {@from body} {@type string} {@required false} {@pattern /^[0-9a-z]{3,10}$/}

Another test also fails..

    {@from body} {@type email} {@required false}

here also the @type email makes it a required variable (`@required false` is not honoured).
(i am using restler 3.0.0 installed with composer)

**Comment by Arul-** [comment]
Can I see the signature for the Api method too? You may make it minimal to just reproduce the issue!

**Comment by pgh70** [comment]
Sorry, i include some more info...

Function:

   /**
     * Send and SMS message
     *
     * Send a SMS message to destination and log to counting database and user history
     *
     * @url POST send
     *
     * @param
     *            smsRecord Details of SMS to send {@from body} {@type smsRecord}
     * @return array Result of sending SMS
     * @access protected
     *
     */
    protected function send($smsRecord)

The smsRecord is defined in a class:

class SMSrecord
{
    /**
     *
     * @var string Service name for which the SMS is sent {@from body} {@type string} {@required true}
     */
    public $service;

    /**
     *
     * @var string Destination phone number of SMS {@from body} {@type string} {@required true} {@pattern /^[+]?[\d]{10,15}$/}
     */
    public $destination;

    /**
     *
     * @var string Message to send {@from body} {@type string} {@required true}
     */
    public $message;

    /**
     *
     * @var string Logincode of person to whom SMS is sent {@from body} {@type string} {@required false} {@pattern /^[0-9a-z]{3,10}$/}
     */
}

I did check meanwhile with the last version from the master branch... same result..

**Comment by Arul-** [comment]
I'm wondering why the type is set to `smsRecord` where as the original class name is `SMSrecord`

**Comment by pgh70** [comment]
Leftover from name change... Fixed it, but doesn't make a change for the issue..

**Comment by pgh70** [comment]
Much simpler example:

```
    /**
     * Test
     *
     * Testfunction
     *
     * @url POST test
     *
     * @param testvar Test variable of lowercase characters {@from body} {@type string} {@required false} {@pattern /^[a-z]{3,5}$/}
     *
     * @return array
     * @access public
     */
    public function test($testvar)
    {
        return array(
            "text" => "test"
        );
    }
```
Without the @pattern the 'testvar' is optional (although in this setup it must be available in the body which is strange too)... With the @pattern an empty value isn't accepted. A null value is excepted, so the required behavior is acting strange...

**Comment by Arul-** [comment]
It is a bug, which will be fixed shortly!

**Comment by pgh70** [comment]
Some additional testing with the initial setup (SMSrecord -> logincode)...
If logincode is missing from the body -> OK
If logincode is present in the body with null value ("logincode" : null) -> OK
If logincode is present in the body with null string ("logincode" : "") -> Not OK

So it seems like there is a test somewhere in the code to see if it is a string (is_string()), and if it is, the pattern is checked... It would be nice to include the check if the sting is not empty.

In the simper example, the need to have the 'testvar' in the body is due to no default value in the function description.. Changing it to:
```php
public function test($testvar = null)
```
makes it behave the same as above.

**Comment by Arul-** [comment]
@pgh70 giving null as the default value is the best option for RC5. Otherwise your default value should match the pattern!

**Comment by RVN-BR** [comment]
@Arul- I realized from the trello that you are focusing on xamples, I'm currently looking for a "best case" scenario of documentation and development for an API... I have the chance of starting an API with some planning first (lol...not literally but this time I can really draw things out etc)...

I'm having some difficulty finding working examples showing complete ways of adding the request and response types, etc, all in restler...

I'm getting lots of stuff from the issues, but it may be a good idea to have a larger "full api" example..

things that have come to mind:

Adding records with a class definition or a simple definition
Class definition with required and optional parameters mixed. 
Class definition with different reqreuiemtents (such as required for POST, optional for PUT)
Document a return that can return different response types? (like a search that can return users and articles... can response have multiuple types?)

**Comment by Arul-** [comment]
@RVN-BR I can give you some solutions for the above. Why don't you open another issue requesting the documentation!
