### ISSUE TITLE
HTTPS Restler but trying to get resource json over port 80

### ISSUE THREAD

**Issue by codemonkeyneo** [Luracast/Restler#437]
I have created a new instance for restler and I will only be exposing it via HTTPS. (port 80 is disable).

I have loaded the swagger UI but then the API end points are not shown as they for some reason are still trying to be pulled by port 80.

    0 : error https:/myaddess:80/resources/resource.json

Any help would be great, Cheers

**Comment by Arul-** [comment]
Can you give you provide me the url so that I can try and find out what's wrong. Contact me privately through arul@luracast.com

**Comment by Arul-** [comment]
As per your private mail, I understand that you use a load balancer that listens in 443 and passes the request to apache on port 81

Just try adding the following in your index.php and let me know if it works

```php
//just overriding the setting before calling $r->handle()

$_SERVER['HTTPS']='on';
$_SERVER['SERVER_PORT']=443;
```
