### ISSUE TITLE
Convert Php object to Xml restler

### ISSUE THREAD

**Issue by KOSSOKO** [Luracast/Restler#438]
Hello, I begin with Restler and i would know if I can automatically serealize (using a restler method for example) a php object to XML without declare each variables, as in the example in the web site. Sorry for my bad English, I'm a French speaker.

**Comment by Arul-** [comment]
You are interested only in the serialisation and not using restler for creating an api server, am I correct?

You can use just the XmlFormat class for that purpose

```php
<?php
include '../vendor/autoload.php';

use Luracast\Restler\Format\XmlFormat;

$source = array( 'name' => 'value' );

$x =  new XmlFormat();
echo $x->encode($source);
```
outputs the following

```xml
<?xml version="1.0" encoding="UTF-8"?>
<response><name>value</name></response>
```

**Comment by RVN-BR** [comment]
You shouldnt double post... (I saw you asked the same question on #410...) anyways,

I'm not sure I udnerstand your question.  If you want to return XML from the API, you should add XML Format to the allowed formats and then just return the array from the function.  Restler "format" class will automatically treat it and encode to json, xml, etc...

on your restler index endpoint, find something like this:

$r->setSupportedFormats('JsonFormat')

and change it to: $r->setSupportedFormats('JsonFormat','XmlFormat'); to include XML.

Then call your API method, like mysite.com/API/Method.xml If you call /API/Method without extension, it would default to the first available supported format (json in this case)

**Comment by RVN-BR** [comment]
@Arul- beat me to the punch.... anyways, I'm not sure what you were looking for... if it was just serialization like he said (mayb its that from the original question I was a bit confused), but if so just ignore my answer...

**Comment by KOSSOKO** [comment]
Thanks
