### ISSUE TITLE
Does Restler V3 support Multiple roles permission?

### ISSUE THREAD

**Issue by pjyong** [Luracast/Restler#439]
Hi Arul
I have created one API system for my users, but now I want to create some new APIs for my managers.
Some of apis can be access by users and managers.
Some of apis just can be access by users.
Some of apis just can be access by managers.
Some of apis can be access by not logged users.

It seems only "protected" can not help me finish above requirements. Do you have any idea for this?
Thanks very much
June

**Comment by Arul-** [comment]
Take a look at the Access Control example in http://restler3.luracast.com/examples/_010_access_control/readme.html

Let me know if you are still unclear how this works

**Comment by pjyong** [comment]
It's solved!!! Thanks very much.
I'm using Oauth token, so I added one filed "role" into my oauth_token table. When some token is passed, I verify that token and get the "role" of that token from database. Other part is same to the example code.
Now it's working fine.

**Comment by Arul-** [comment]
@pjyong glad you resolved it :+1:
