### ISSUE TITLE
Restler annotation for personnal route

### ISSUE THREAD

**Issue by KOSSOKO** [Luracast/Restler#441]
I'm trying to have a personnal route to access my API classe. But I don't understand well the example of annotation in the web site of restler. 
I can access my API class with this link for example 
http://eztko.cnrgv.toulouse.inra.fr/ezpublish-ws.php/PrestationWs/lirePrestation?id=1119

but I want to do http://eztko.cnrgv.toulouse.inra.fr/ezpublish-ws.php/prestation/119
so in the my class I did 

```php
    /**
     * @url GET prestation/{id}
     * Cette méthode retourne une array qui peut être sérialisé en xml par Restler
     * @param $id
     * @return La prestation et les autres classes liées, dans un tableau pour la serialisation en xml par restler
     * 
     */
    function lirePrestation($id)
    {
        $p = new Prestation();
        $pSvc = new PrestationSvc();
        $p = $pSvc->lireToArrayAssoc($id);
        $tab = array($p); //convert to array before sending it to restler for xml
        return  $tab;
    }
```

but I got when i try my link a 404 noy found. 
My index is ezpublish-ws.php in my link. How could I do that ? thanks

**Comment by Arul-** [comment]
Is your app still live? can I try the url myself?

**Comment by KOSSOKO** [comment]
yes, but i don' think that link could be accessible outside where i work

**Comment by Arul-** [comment]
Then I'm afraid I can't be of much help. your example should work as it is! so not sure where the problem is!

**Comment by KOSSOKO** [comment]
I just know find the problem. Restler doens't support annotation like @param or @return. So i remove all comments and chage the name of API's classes by get, put and it works.

**Comment by Arul-** [comment]
restler does support @param and @return, they just need to include the type, that could be your problem. Try

```php
     /**
     * @url GET prestation/{id}
     * Cette méthode retourne une array qui peut être sérialisé en xml par Restler
     * @param int $id
     * @return array La prestation et les autres classes liées, dans un tableau pour la serialisation en xml par restler
     * 
     */
    function lirePrestation($id)
    {
        $p = new Prestation();
        $pSvc = new PrestationSvc();
        $p = $pSvc->lireToArrayAssoc($id);
        $tab = array($p); //convert to array before sending it to restler for xml
        return  $tab;
    }
```

**Comment by KOSSOKO** [comment]
yes it works. thanks a lot.

**Comment by KOSSOKO** [comment]
But now i'm trying to implement put method, and i got content type text/plain is not supported. I'm trying to send an xml string. I found a topic about that but the discussion turs around RC4
