### ISSUE TITLE
Namespace Issue With External Libraries

### ISSUE THREAD

**Issue by mnorby1** [Luracast/Restler#442]
I am currently trying to get a new library to work with Restler.  The problem I am having is including the namespace of the other library.

I know the other library is included and works properly as I can use it inside of global space in all of the files.  However as soon as there is a class that restler uses I am not able to access the libraries classes or functions.

The way I have restler setup is:
index.php includes restler.php
which adds class `$r->addAPIClass("MyAPIClass")`;
inside of the MyAPIClass file I am able to use the external library just fine in global namespace.  But inside of class MyAPIClass{} I am not able to find the external library functions at all. The external libaray I am working with is rackspace opencloud.

My File looks like this:
```php
<?php
require_once(__DIR__ . "/../../lib/vendor/autoload.php");
use OpenCloud\Rackspace;

//This works perfectly fine
$client = new Rackspace();

class MyAPIClass{
    public function __construct(){
       //Gives this error: PHP Fatal error:  Class 'OpenCloud\Rackspace' not found
        $client = new Rackspace();
    }
}
```

I have also tried to use the namespace differently such as:
`use OpenCloud\Rackspace as MyTestNamespace;`
which does not work either as inside of my class it cannot find the MyTestNamespace.

Has anyone come across this issue before?  Or know why anything inside of Restler is not able to access the other libraries class.  Thanks for any insight and help you can provide.

**Comment by Arul-** [comment]
are you installing both restler and rackspace using composer?

**Comment by mnorby1** [comment]
No, actually I am not.  I have installed restler as a submodule inside of git.  I have looked into installing it with composer; though I would have to change my directory structure quite a bit to have restler as the top level of the project instead of a library of the project.  If that is the problem I will look into changing my directory structure to have both installed with composer.

**Comment by Arul-** [comment]
Yes! if you manage your dependencies with composer you won't face any issue like this
