### ISSUE TITLE
Logging API requests?

### ISSUE THREAD

**Issue by RVN-BR** [Luracast/Restler#444]
Hi Guys,

I'd like to know if anyone has had experience doing api access logging?  I'm weary of anything which runs "on every request" but I'd like to get some level of logging into elk.

I suppose using Events would be the best?  Is there any performance hit on that?

Also, can anyone share their own implementations, patterns, practices for this?  I recently noticed that MailChimp has a "last accesses" to their API list... its quite cool for debugging and such, but it got me thinking due to high volumes its not that trivial...

Finally, has anyone looked at kong? any good stuff to inspire development for R3?

**Comment by Arul-** [comment]
Does #385 help?

**Comment by RVN-BR** [comment]
Hi @Arul- yes - and no.. hehe...

The method described in #385 seems to be one of the ways of doing, but my question is more regarding the experience of people who have done it.  Have you taken a big performance hit? or a performance hit at all?

is onComplete running after the return has gone to the browser, or just prior?

thanks!

**Comment by Arul-** [comment]
> is onComplete running after the return has gone to the browser, or just prior?

right after sending it but before closing the connection

**Comment by RVN-BR** [comment]
Right, but there is no buffer flush or anything right? so it would still hold the response time if the logging addedd some time, right?

**Comment by Arul-** [comment]
For an example for logging see http://stackoverflow.com/questions/31853608/how-to-log-all-requests-in-php-restler-3/31883204#31883204

```php
use Luracast\Restler\Restler;
use Luracast\Restler\User;

$r = new Restler();
$r->onCall(function () use ($r) {
    // Don't log Luracast Restler Explorer recources calls
    if (!preg_match('/resources/', $r->url)) {
        $info = array(
            'base'    => $r->getBaseUrl(),
            'method'  => $r->requestMethod,
            'url'     => $r->url,
            'route'   => $r->apiMethodInfo->className . '::' . $r->apiMethodInfo->methodName,
            'version' => $r->getRequestedApiVersion(),
            'data'    => $r->getRequestData(),
            'ip'      => User::getIpAddress(),
        );
        print_r($info);
    }
});
$r->addAPIClass('Say');
$r->handle();
```

**Comment by Arul-** [comment]
There are many php libraries for php queue processing and running workers

For example https://packagist.org/search/?q=php%20worker

We can use them in the above example to log without delaying the response!
