### ISSUE TITLE
Guzzle Depreciated?

### ISSUE THREAD

**Issue by srsgores** [Luracast/Restler#449]
I am new to composer and restler, but I am unable to run tests, after following the documentation on the readme.  Using PHPStorm and a run configuration, I get the following:

> "C:\Program Files (x86)\Ampps\php\php.exe" C:\Users\sean\AppData\Local\Temp\ide-behat.php --format PhpStormBehatFormatter C:\Users\sean\Documents\api\features
Testing started at 10:05 AM ...

> Fatal error: Class 'Guzzle\Service\Client' not found in C:\Users\sean\Documents\api\features\bootstrap\RestContext.php on line 47
PHP Fatal error:  Class 'Guzzle\Service\Client' not found in C:\Users\sean\Documents\api\features\bootstrap\RestContext.php on line 47

> Process finished with exit code 255

I have installed all dependencies, so either ``guzzle`` was just there for example purposes, or it's now depreciated, and should be removed.

Am I missing something?

**Comment by RVN-BR** [comment]
I'm not sure how the tests are right now, but I do know Guzzle is alive and kicking :)

I'd check if composer did indeed download and is able to load guzzle correctly?  Sounds more like a composer issue from the error... not sure...

**Comment by csiszarattila** [comment]
Try composer with installing [dev packages](http://stackoverflow.com/questions/16679589/whats-the-difference-between-require-and-require-dev) too:
```
composer install --dev
```

**Comment by Arul-** [comment]
Did you try as @csiszarattila suggested?

**Comment by srsgores** [comment]
I have't configured composer globally, so doing ``composer install --dev`` won't work for me.  But I did install ``guzzlehttp``, and I still get the same error:
![image](https://cloud.githubusercontent.com/assets/1750837/8009565/f972ccaa-0b66-11e5-9663-cb5b20addcc8.png)

**Comment by Arul-** [comment]
This issue should be fixed now! please check and reopen the issue if not fixed
