### ISSUE TITLE
CsvFormat type didnt seem to work 

### ISSUE THREAD

**Issue by codemonkeyneo** [Luracast/Restler#452]
I wanted to return a CSV format for some of my API's as well as JSON / XML. The data is pretty large so I have added a generic way to page the data with navigation links available following the whole HATEOS methodology.

The csv format wasn't be returned and I just ended up with a white screen and ERR_INVALID_RESPONSE.

I worked out it must have been because of the extra layout and the CSV needed to be kept in to something simple that could represent tabular data.

I have now added the extra code in the API's to check if the request is for the csv format and then only return the data part instead of additional information.

```php
    $url = $_SERVER['REQUEST_URI'];

    $qpos = strpos($url, "?");
    $dpos = strpos($url, ".") + 1;

    $format_extension_length = $qpos - $dpos;

    $format = substr($url, $dpos, $format_extension_length);
    
    if ($format == "csv") {
      $result = $data; // only return the data part that can be represented tabular.
    }
    
    return $result;
```

Is this a bit of a Hack ? should be done differently ? Any feedback would be appreciated.

Cheers

**Comment by codemonkeyneo** [comment]
Hi Arul,

Just wondering where in the request does Restler work out what type is being requested ?

**Comment by Arul-** [comment]
You can add the following code in your api method to check the response format

```php
if ($this->restler->responseFormat->getExtension() == 'csv') {
    return $justTheTabularData
}
return $dataIncludingMetadata;
```

**Comment by letsbyteit** [comment]
@Arul- You might want to document this. I really didn't know about CsvFormat in the first place. But I forgot about the "simple" data structure, that I've to return. Please emphasise this point.
