### ISSUE TITLE
Fatal error: Unsupported operand types in /Restler/vendor/Luracast/Restler/Routes.php on line 554

### ISSUE THREAD

**Issue by ernestu** [Luracast/Restler#453]
+= operation on array  at  line 554 in /Restler/vendor/Luracast/Restler/Routes.php 

```php
        $child = array('name' => $name);
        if ($c = $prop->getDocComment()) {
             $child += Util::nestedValue(CommentParser::parse($c), 'var');
```

**Comment by csiszarattila** [comment]
This can be reproducible if you have an uncommented property in one of your model classes. eg.:
```
class Model 
{
  public $property;
}
```
Fix this with adding a comment to your property:

```
class Model
{
 /**
 * @var string My awesome property
 */
 public $property;
}
```

However a more meaningful error message would be nice.

**Comment by Arul-** [comment]
It looks like a bug that needs fixing. Thanks for reporting :+1:

**Comment by Arul-** [comment]
I digged further into it, actually not adding comment to a model property does not cause it! It happens only when you add a comment to a model property with out `@var`

**Comment by fernandoc2** [comment]
Seems the last change made, it is causing other issues:

PHP Parse error:  syntax error, unexpected '[' in ... /vendor/luracast/restler/vendor/Luracast/Restler/Routes.php on line 554
