### ISSUE TITLE
Upgrade to latest Guzzle 3.x

### ISSUE THREAD

**Issue by tallsam** [Luracast/Restler#454]
According to https://github.com/guzzle/guzzle Restlers current version of Guzzle is EOL'd.

Also I'm hitting a bug where its impossible to completely disable SSL certificate checking (I'm using a self-signed cert in dev). See  Http/Client.php line 141 - that should be a 0 instead of a 2.

**Comment by tallsam** [comment]
The composer package for guzzle is now guzzlehttp/guzzle

**Comment by tallsam** [comment]
Actually all I would need to get around this bug is an upgrade to 3.8.1.

https://github.com/guzzle/guzzle/commit/83d982ba7710c73a04ca19b2c45d0cd3fb3a78b3

**Comment by Arul-** [comment]
Fixed in b01f94fe5488151ee5efd1fa13dcc397ce79a230 the latest RC6
