### ISSUE TITLE
Output format in the middle of URL when using arguments.

### ISSUE THREAD

**Issue by tallsam** [Luracast/Restler#456]
If i have

```@url GET science/soilwater/{stationId}/{soilId}```

Then I would expect the URL for the endpoint to be
```
science/soilwater/12/1.json
```
But Restler is forcing it to 
```
science/soilwater.json/12/1
```

Is this by design?

**Comment by Arul-** [comment]
Actually both the endpoints work with restler

I guess you are referring to the Explorer. Yes Explorer is configured to act that way

You can change that behavior by adding the following to `index.php`

```php
use Luracast\Restler\Resources

Resources::$placeFormatExtensionBeforeDynamicParts = false;
```

If you are using RC6 or higher use ` Luracast\Restler\Explorer\$placeFormatExtensionBeforeDynamicParts` instead

**Comment by tallsam** [comment]
Awesome thanks a bunch!
