### ISSUE TITLE
Cannot run the live API in REST Client Addon of Chrome it gives error : Forbidden: Content type `text/plain` is not supported.

### ISSUE THREAD

**Issue by ramanroy911** [Luracast/Restler#459]
I am trying to test post request in REST Client chrome addon but I am facing error 

Forbidden: Content type `text/plain` is not supported.

How can I resolve it?

**Comment by Arul-** [comment]
This is happening because explorer sends the request with content type text/plain when there is no body

For now just make sure you specify a body parameters while testing!  We will find a better solution soon!
