### ISSUE TITLE
issue in jsonencode url

### ISSUE THREAD

**Issue by shamseerpari** [Luracast/Restler#462]
any one please help me to resolve this,
$url = 'http://www.example.com/';
echo json_encode($url);
forward  slashes coming with the result,how can i get the exact result

the only solution that i got when googled
echo json_encode($url, JSON_UNESCAPED_SLASHES);
this function only supported php 5.4 onwards,in current server php version below this

**Comment by Arul-** [comment]
Use JsonFormat instead, it works starting from PHP 5.3

```php
use Luracast\Restler\Format\JsonFormat;

$format = new JsonFormat();
JsonFormat::$unEscapedSlashes = true;
$url = 'http://www.example.com/';
$format->encode($url);
```
