### ISSUE TITLE
Fix breaks PHP version dependency

### ISSUE THREAD

**Issue by pgh70** [Luracast/Restler#471]
The bugfix for issue #453 (commit ca3f2c46) breaks dependency for given PHP version. The [] construct requires PHP 5.4 (http://nl1.php.net/manual/en/language.types.array.php). Use array() in stead of [] to be compliant with the stated PHP version (PHP >= 5.3.2).

**Comment by Arul-** [comment]
thanks for reporting :+1:  Fixed it now!
