### ISSUE TITLE
Failed opening required '../vendor/restler.php' (include_path='.;C:\php\pear')

### ISSUE THREAD

**Issue by ilhanyumer** [Luracast/Restler#472]
```html
<br />
<b>Warning</b>:  require_once(../vendor/restler.php): failed to open stream: No such file or directory in <b>E:\asistan\api\public\index.php</b> on line <b>17</b><br />
<br />
<b>Fatal error</b>:  require_once(): Failed opening required '../vendor/restler.php' (include_path='.;C:\php\pear') in <b>E:\asistan\api\public\index.php</b> on line <b>17</b><br />
```
I have noticed that this issue appears in the very first request. Like I open the Windows 7, I start EasyPHP with PHP 5.5.20, I open Firefox, and after I open the application it request `GET` to `http://touch.ilhan/api/servisdurumu?_dc=1438929457897&page=1&start=0&limit=25` I get the above error. It is not related with `ServisDurumu.php` but the very first load.

My [php.ini](https://gist.github.com/ilhanyumer/ee03b8789c8452a9a764), [autoload_namespaces.php](https://gist.github.com/ilhanyumer/26df2bed70788bd0dec6), [composer.lock](https://gist.github.com/ilhanyumer/546893f0f0554c49562b).

Note that I have not installed any pear.

**Comment by Arul-** [comment]
How did you install Restler? did you download and unzip from GitHub?

**Comment by ilhanyumer** [comment]
@Arul- I don't remember but after that I have run Composer few times to install some other things.

**Comment by Arul-** [comment]
Check if you have `restler.php` in your vendor directory, if not, you can do the following in your index.php instead

```php
$loader =  require('../vendor/autoload.php');
$loader->setUseIncludePath(true);
```

That should get you going!

**Comment by ilhanyumer** [comment]
Yes, I have `restler.php`.
![restler.php](http://i.imgur.com/cyO2EBT.png)

Now, I think it is something to do with Behat.
![Behat](http://i.imgur.com/4Xs6FqL.png)
