### ISSUE TITLE
Can I change how errors get serialized?

### ISSUE THREAD

**Issue by kitsunde** [Luracast/Restler#473]
Currently the response is sent like:

    {
      error: {}
    }

I don't need the `error` attribute and the only way I can see that I can add data is through the `$detail`, but I need to serialize errors to be jsonapi.org compliant:
  
    {
      errors: [
        {
          details: "Some validation is wrong",
          "source": {"pointer": "/data/attribute/someattribute"}
        }
      ]
    }

**Comment by Arul-** [comment]
Composer class is responsible for that. By implementing iCompose interface, you can create your own Composer class that responds the way you want. Alternatively you can extend the Composer class and override the `message` method. Then make it the default composer class with the following code

```php
//in your index.php
use Luracast\Restler\Defaults

Defaults::$composeClass = 'Luracast/Restler/JsonApiComposer';

//...
```

If you think this new composer class will be of use to other restler developers, submit a pull request to v3 branch :+1:
