### ISSUE TITLE
is restler unmaintained?

### ISSUE THREAD

**Issue by eriknyk** [Luracast/Restler#474]
I'm so curious regarding to:
version 3.0 will be releases sometime in the future?

the README was updated adding RC5 notes on Apr 14, 2014
(https://github.com/Luracast/Restler/commit/827a532d4a41803559bb248f489bbce71f81feaa#diff-04c6e90faac2675aa89e2176d2eec7d8 )

until now it passed more than one year,
this is not a long time to still stay on rc5?

the next is an rc6, or we can wait for an 3.0 release?,..
I'm using this great library, I wish to know what is future of it.

Best Regards.

**Comment by RVN-BR** [comment]
The readme is probably the worst place for seeing progress as its (unfortunately - as in many projects), the last part to be updated. 

Check the commit history as well as ongoing discussions and you will see its quite the contrary

**Comment by Arul-** [comment]
We are actively working on Restler, just need more helping hands to make things faster ;)

**Comment by ksnyde** [comment]
I think one thing considering Restler is that all graphs/metrics are based off "master" so it does look like its lost its momentum which will scare away new users. If for no reason other than momentum and ensuring people aren't scared off I would say getting a release to `master` would be a good idea.

Here's the graph most people will look at when evaluating to invest in Restler:

![image](https://cloud.githubusercontent.com/assets/980757/9514805/051f0d42-4c95-11e5-8281-e9488be649e0.png)
