### ISSUE TITLE
Document response type doesn't seem to work

### ISSUE THREAD

**Issue by codemonkeyneo** [Luracast/Restler#477]
I would like to add a more descriptive return type to my API instead of simply array.

I have changed the API to return a custom class called 'Station' and defined the class as follows ;

    class Station {
      /** 
       * @var string $id unique identifier for a station 
       * @var string $name name of station
       * @var decimal $latitude gps lat point
       * @var decimal $longitude gps long point
       */
         public $id;
         public $name;
         public $latitude;
         public $longitude;
    }

However in explorer it simply shows

Station ( id: decimal, name: string, latitude: string, longitude: string )

Ideally I would this to show that it is an array of stations

array( station {
    id unique identifier for a station,
    name name of station,
    latitude gps lat point,
    longitude gps long point
})

but most importantly have the descriptions for the properties.

Is this the correct approach or is their a better way of showing a more descriptive return type for the data being returned.

Cheers

Neil

**Comment by Arul-** [comment]
I guess you tried the explorer in RC6, which is still under construction!

Soon you will be able to see the full description, in fact the swagger 2 branch has a version that does it!

**Comment by codemonkeyneo** [comment]
Cheers Arul will check out the swagger 2 branch, at least I must have made some sense :).

Cheers
