### ISSUE TITLE
Required properties by default,..is an ISSUE? on with RC6

### ISSUE THREAD

**Issue by eriknyk** [Luracast/Restler#483]
Hello
I think that I've an issue after update from RC4 to RC6

I have the following class to map the body contents of a PUT method def.

``` php
class ActivityData
{
    /**
     * @var string {@from body} {@min 1} {@max 200}
     */
    public $title;

    /**
     * @var string {@from body}
     */
    public $description;     
    ...
}
```

and using it into a class method

``` php
class Test
{
    /**
     * @param string $uid {@min 32} {@max 32}
     * @param ActivityData $properties {@from body}
     * @url PUT /activity/:uid
     */
    public function doPut($uid, ActivityData $data, $request_data =  array())
    {
       ...
    }
    ...
```

any property of ActivityData is required, It was working on Restler3-RC4
but since I've updated to Restler3-RC6 it is not working as before
now I'm getting an error that says: $title and $description are required,

the only way to make this works as before is setting required attr to false, as following:

``` php
class ActivityData
{
    /**
     * @var string {@from body} {@min 1} {@max 200}  {required false}
     */
    public $title;

    /**
     * @var string {@from body}  {required false}
     */
    public $description;     
    ...
}
```

The problem is that we won't to change all already defined classes,. that are a lot of classes,..
so the only way is make a downgrade to RC4,..
I'm not sure if consider properties required by default is the desired behaviour on RC6 or it is an issue.

Best Regards.

**Comment by Arul-** [comment]
RC6 gives you the flexibility of choosing the properties that you want to capture and required properties among that at the api method level, say for example


```php
class Test
{
    /**
     * @param string $uid {@min 32} {@max 32}
     * @param ActivityData $properties {@from body}{@properties title,description}{@required title}
     * @url PUT /activity/:uid
     */
    public function doPut($uid, ActivityData $data, $request_data =  array())
    {
      // ...
    }
    // ...
```
Marks that title and description are the properties to capture on ActivityData and title is a required property

In your case you can just do the following

```php
class Test
{
    /**
     * @param string $uid {@min 32} {@max 32}
     * @param ActivityData $properties {@from body}{@required none}
     * @url PUT /activity/:uid
     */
    public function doPut($uid, ActivityData $data, $request_data =  array())
    {
       //...
    }
    //...
```
to mark that none of the properties are required.

Let me tell you an use case for this feature

You can use the same User class in both login and signup methods but login method will capture only email and password, where as register will capture all properties

**Comment by infabo** [comment]
How can I use @properties if e.g. ActivityData has a property with another valueobject?

```
class User
{
    /**
     * @var string {@min 1} {@max 200}  {required true}
     */
    public $name;

    /**
     * @var string {@min 1} {required true}
     */
    public $description;
    ...
}

class ActivityData
{
    /**
     * @var string {@from body} {@min 1} {@max 200}  {required false}
     */
    public $title;

    /**
     * @var string {@from body}  {required false}
     */
    public $description;

    /**
     * @var User {@from body}  {required false}
     */
    public $user;     
    ...
}
```

No I want to say, "description" property of User should not be captured.

```
class Test
{
    /**
     * @param string $uid {@min 32} {@max 32}
     * @param ActivityData $properties {@from body}{@properties title,description,user}{@required title}
     * @url PUT /activity/:uid
     */
    public function doPut($uid, ActivityData $data, $request_data =  array())
    {
      // ...
    }
    // ...
```

How has the annotations to be look like? Is this even possible?

**Comment by infabo** [comment]
Another issue with @properties.
If this annotation is used, the listed properties are only checked for existence - but not for their type anymore.
Say I provide a boolean for the title attribute, but it should be a string. It throws no validation error anymore.

**Comment by Arul-** [comment]
We have added a way to override the properties and their required status by specifying magic properties

For example

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Review
 *
 * @property-read  int    $id
 * @property       string $name
 * @property       string $email
 * @property       string $message
 * @property-read  string $created_at {@type date}
 * @property-read  string $updated_at {@type date}
 * 
 */
 class Review extends Model
{
  //...
} 
```
