### ISSUE TITLE
Syntax error on v3 with php 5.3.3

### ISSUE THREAD

**Issue by Tommyf** [Luracast/Restler#484]
I was trying to get v3 rc6 working on my work machine (with php 5.3.3 - RHEL 5.1) and got the following error:

    PHP Parse error:  syntax error, unexpected '[' in /path/to/restler/vendor/Luracast/Restler/Routes.php on line 667

I notice that **array()** has been replaced with **[]**

Is there a reason for this? I changed it back and it still works, but I may be missing something. Seems to be introduced a year ago tomorrow in: https://github.com/Luracast/Restler/commit/4d0aff23e976a4ed1cf9d5cd2e5f781a84ac8c97

I'm working on my pull request for https://github.com/Luracast/Restler/issues/479 / https://github.com/Luracast/Restler/pull/480 and will include this fix there.

Thanks,

Tom...

**Comment by Tommyf** [comment]
It seems the short array syntax **"[]"** was introduced in php 5.4. If you want to maintain 5.3 compatibility as per the readme, it needs to be **"array()"**

From: http://php.net/manual/en/language.types.array.php

> As of PHP 5.4 you can also use the short array syntax, which replaces array() with [].

I have fixed it in: https://github.com/Tommyf/Restler/commit/0d111c6f7171bceb786fa7175434acda1edbbca6

**Comment by Arul-** [comment]
closing this as we already merged the solution!
