### ISSUE TITLE
A unit test case for event dispatcher

### ISSUE THREAD

**Issue by andytruong** [Luracast/Restler#486]
I try to listen to the 'respond' (and other) event, but failed, only 'negotiate' is working. There's no docs for this.

```php
$application = new \Luracast\Restler\Restler($production, $refresh = false);
$application->on([
    'negotiate' => function () {
        print_r([__FILE__ . ':negotiate']);
    },
    'response'  => function () {
        print_r(__FILE__ . ':response');
    }
]);

$application->handle();
```

**Comment by Arul-** [comment]
Restler is about efficiency, it tries to avoid taking bad api calls all the way to response as early as possible

so don't expect all the events in every call, only the stages that a particular api call passes through are fired
