### ISSUE TITLE
doc comments for field validation & input validation

### ISSUE THREAD

**Issue by roydekleijn** [Luracast/Restler#487]
Hello,

Is it possible to use the doc comments for field validation & input validation ?
Field validation like: _validate() in (https://github.com/Luracast/Restler/blob/e2b0b8e1974f5584b37a567f4cc127578ce473c5/public/examples/_007_crud/Authors.php)

Input validation like: length (min, max), alpha_numeric check, check based on regex.

**Comment by Arul-** [comment]
I can see how this can be useful :+1: 

It can me made possible without much effort, will definitely look into it!

**Comment by roydekleijn** [comment]
Please let me know how/if I can contribute.

**Comment by roydekleijn** [comment]
Any update on this?

**Comment by Arul-** [comment]
We need to have a way to mark an api parameter to enable field validation. It can be done with the following comment

    @param string $name {@validate unique-name}

This will expose an api 

    PUT {className}/unique-name

Which will accept one parameter called $value and return boolean `true` indicating the success. it will return an error response which contains the message to be displayed along with the field.

-------------

Does this sound good to you?

You proceed to make a pull request on v3 branch

If you need help with the next steps, let me know!

**Comment by roydekleijn** [comment]
I meant something like this: https://github.com/Wixel/GUMP

Those are very flexible. Is it possible to implement something like that? and then have the rules in phpdoc.

**Comment by Arul-** [comment]
Have you seen the validation parameters in http://restler3.luracast.com/param.html#min----max ?

We have a validation class that does what you ask for!
