### ISSUE TITLE
Api prefix removed from RC5

### ISSUE THREAD

**Issue by linux019** [Luracast/Restler#490]
In RC4 there was apiPrefix, but it was removed in RC5.
This api function we call for payments

```
https://host/gateway/v1/pay.json
```

I need api prefix, because the framework installed in different folder rather than 'gateway' name
So I added hack to index.php to resolve this problem.

```
$apiPrefix = '/gateway';

if (strpos($_SERVER['REQUEST_URI'], $apiPrefix) === 0)
$_SERVER['REQUEST_URI'] = substr($_SERVER['REQUEST_URI'], strlen($apiPrefix));
```

The baseUrl should also contains the api prefix.
Can you return back setApiPrefix from RC4?

**Comment by Arul-** [comment]
We are no longer supporting that feature!
