### ISSUE TITLE
Base url should be taken from $_SERVER['HTTP_HOST'] instead of $_SERVER['SERVER_NAME']

### ISSUE THREAD

**Issue by devbazilio** [Luracast/Restler#491]
RC5 
https://github.com/Luracast/Restler/blob/e2b0b8e1974f5584b37a567f4cc127578ce473c5/vendor/Luracast/Restler/Restler.php#L451

I have server, that hosts several virtual hosts. Names of those hosts differs from server name and baseUrl incorrectly set to machine name

**Comment by Arul-** [comment]
Because $_SERVER['HTTP_HOST']  is set by the client it can't be trusted. We need to use a pre approved list to validate against. 

Here is what you need to do

```php
$r = new Restler();

$r->setBaseUrls(
    'https://mydomain.com',
    'https://mydomain.biz',
    'https://mydomain.us',
    'https://somedomain.in',
    'http://localhost:8000'
);

// ...
```
