### ISSUE TITLE
implement refresh token

### ISSUE THREAD

**Issue by roydekleijn** [Luracast/Restler#495]
Hi,

I try to implement JWT (Json webtoken), therefore I implemented AccessControl.
I wonder how I can send a refreshed token in the response (header) if the original token was not expired.

Please provide me some guidance with implementing a refresh token and send a response with a new bearer token.

__
Roy

**Comment by Arul-** [comment]
How did you implement your AccessControl so far? Can we see the code?

**Comment by Arul-** [comment]
Re-open this issue when you are ready to share your existing code and talk further
