### ISSUE TITLE
missing dot in include_path

### ISSUE THREAD

**Issue by posipa** [Luracast/Restler#496]
Your system assumes, that there is always, by default, a dot in include_path. 
But it is not always like that. 
If dot is missing in include_path by default, you will always get 404 as I did.
I've spent few days digging in code and I hope someone else won't ;)

**Comment by Arul-** [comment]
@posipa thanks a lot for your input, how do we reproduce it on our end?

set the include path manually to remove the "." and then call any api?

Little more explanation will help

**Comment by posipa** [comment]
I had something like this in my php.ini
include_path = "C:\xampp\php\ext;C:\xampp\php\PEAR"
and it causes problem

I've changed to 
include_path = ".;C:\xampp\php\ext;C:\xampp\php\PEAR"
and it worked

**Comment by Arul-** [comment]
What kind of problem is caused? none of the exposed api work? all of them return 404?

**Comment by posipa** [comment]
Anything I've typed as arguments in url I got

for example: 

http://myapi.localhost/my_api/public/GetMeSomething/index?id=69

returned 


{
    "error": {
        "code": 404,
        "message": "Not Found"
    },
    "debug": {
        "source": "Routes.php:431 at route stage",
        "stages": {
            "success": [
                "get"
            ],
            "failure": [
                "route",
                "negotiate",
                "message"
            ]
        }
    }
}

**Comment by CarstenSchmitz** [comment]
posipa you made my day. That's been exactly my problem when copying my app from linux to windows xampp. Linux all fine, Windows no routes any more...

**Comment by Arul-** [comment]
This is no longer apply!
