### ISSUE TITLE
Content-Type shouldn't be sent with HTTP 204?

### ISSUE THREAD

**Issue by shaneneuerburg** [Luracast/Restler#501]
Another library, [Siesta for iOS](https://github.com/bustoutsolutions/siesta/issues/11#issuecomment-156788623), expects an HTTP 204 to not include the Content-Type (or, I should say that if that is present, they try to parse the non-existent body).

The [RFC states the following](http://tools.ietf.org/search/rfc2616#section-7.2.1):

> Any HTTP/1.1 message containing an entity-body SHOULD include a
>    Content-Type header field defining the media type of that body.

While it doesn't explicitly state that the header shouldn't be sent if there is no body, it only states that it should if the body exists.

I'd suggest moving the [Content-Type generation logic](https://github.com/Luracast/Restler/blob/master/vendor/Luracast/Restler/Restler.php#L1040-L1048) after the [status code assignment](https://github.com/Luracast/Restler/blob/master/vendor/Luracast/Restler/Restler.php#L1068), with it wrapped in a conditional where `$code != 204`.

Thoughts?

**Comment by Arul-** [comment]
While we think about the long term solution for this problem, you can easily implement a quick fix

Compose class is responsible for final response, so you can create a custom Compose class by implementing `iCompose` interface and then set `Defaults::$composeClass` to the class name of your custom class. Here is an example

```php
class CustomCompose implements iCompose
{
    public static $includeDebugInfo = true;
    public $restler;

    public function response($result)
    {
        if ($this->restler->responseCode == 204) {
            return '';
        }
        return $result;
    }

    public function message(RestException $exception)
    {
        $r = array(
            'error' => array(
                    'code' => $exception->getCode(),
                    'message' => $exception->getErrorMessage(),
                ) + $exception->getDetails()
        );
        if (!Scope::get('Restler')->getProductionMode() && self::$includeDebugInfo) {
            $r += array(
                'debug' => array(
                    'source' => $exception->getSource(),
                    'stages' => $exception->getStages(),
                )
            );
        }
        return $r;
    }
}
```
