### ISSUE TITLE
Fatal error: Cannot use Luracast\Restler\Data\String as String because 'String' is a special class name in C:\git\r3\vendor\Luracast\Restler\Routes.php on line 5

### ISSUE THREAD

**Issue by ganeshkbhat** [Luracast/Restler#505]
Getting a fatal error in your first example.

Fatal error: Cannot use Luracast\Restler\Data\String as String because 'String' is a special class name in C:\git\r3\vendor\Luracast\Restler\Routes.php on line 5

Attached screenshot of PHP Development server logs. Same for Apache Server.

![php fatal error - string class name](https://cloud.githubusercontent.com/assets/3424344/11322012/3618aa88-90fc-11e5-8d03-00ec3f11788d.png)

**Comment by Arul-** [comment]
I guess you are using newer version of PHP (and or on Windows) and Restler RC5, they are not compatible. Use RC6 instead

With RC6 String class is renamed to Text to resolve this issue

**Comment by ganeshkbhat** [comment]
Can you guide me to the master path of RC6. I am able to download just RC5 with String Class. I am on PHP 7.0 RC

**Comment by ganeshkbhat** [comment]
You can close this. Worked with Composer.
