### ISSUE TITLE
Documentation on Models usage?

### ISSUE THREAD

**Issue by igorsantos07** [Luracast/Restler#506]
I'm coming from Restler 2 (two years without using it, with good memories tho), and currently using 3.0-RC6. I've noticed at some places (like the Response Class) mentions on "Models", but found nothing on that in the [docs](http://restler3.luracast.com/).

Specifically I'm having trouble documenting my body parameters: on Restler 2 all parameters were grouped in a JSON textarea. Now I'm getting a blank textarea with the parameter called "CartModel1" (the API class is Cart). If I manually write the correct JSON, it still works, but how do I get the old behaviour of joining together the body params in the text area as a sample?

Restler 3.0-RC6:
![screenshot_523](https://cloud.githubusercontent.com/assets/532299/11922342/4bdd4f94-a77d-11e5-9d6c-14dfad457e1f.jpg)

Restler 2.0, expected behaviour:
![screenshot_522](https://cloud.githubusercontent.com/assets/532299/11922321/386cde70-a77d-11e5-8bdf-022faa574e2a.jpg)

Excerpt of the PHPDoc:

```
    /**
     * @param string $item {@from body} The item name
     * @param float $price {@from body} The item price
     */
```

**Comment by grosch** [comment]
Under Data Type you should see a "model schema" link.  Click on that, and then click in the schema and it'll fill in the text field for you with the right values.

Based on the color of your screenshots I'm guessing this is a PUT item.  PUT by defaults comes from the body, so you don't have to say {@from body} on those parameters in your header comments.

**Comment by Arul-** [comment]
Please reopen if needed
