### ISSUE TITLE
Calling a POST method on the explorer actually issues GET call

### ISSUE THREAD

**Issue by igorsantos07** [Luracast/Restler#509]
I'm running the RC6. POST requests issue a `405 Method not allowed` response. Other methods seem to work as well, such as GET or PUT. Seeing through the console, it actually issued a GET request.

It took me forever to figure this out by myself x____x

**Comment by igorsantos07** [comment]
I can still use the API through my clients, but I can't see how to fix the Explorer. Even by using `@url` it still calls without the trailing slash

**Comment by igorsantos07** [comment]
Actually it seems the explorer is wrongly calling GET on the POST method.

**Comment by Arul-** [comment]
> Actually it seems the explorer is wrongly calling GET on the POST method.

That's weird. How can I reproduce this?

**Comment by igorsantos07** [comment]
Try creating a class with a POST method but no GET method. I simply created
a `function post($user, password)` for my auth class. Then, "Try it" in the
explorer. Seeing the console, it issues a GET and that replies with a
METHOD NOT ALLOWED (obviously, the class do not have a GET method).


*Igor Santos*
Desenvolvedor web / mobile
igorsantos.com.br <http://www.igorsantos.com.br>

**Comment by Arul-** [comment]
I could not reproduce the issue. Here are the exact steps I followed

## Installation

Command on the terminal:
```
composer create-project restler/application=dev-basic explorer_test
```

Result:
```
Installing restler/application (dev-basic db6e6d1b88905a2b868d7b51cb103e084d8c018b)
  - Installing restler/application (dev-basic basic)
    Cloning basic

Created project in explorer_test
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing restler/framework (3.0.0-RC6)
    Downloading: 100%         

restler/framework suggests installing bshaffer/oauth2-server-php (If you want to use OAuth2 for authentication)
restler/framework suggests installing illuminate/view (If you want to use laravel blade templates with Html format)
restler/framework suggests installing mustache/mustache (If you want to use mustache/handlebar templates with Html format)
restler/framework suggests installing rodneyrehm/plist (If you need Apple plist binary/xml format)
restler/framework suggests installing symfony/yaml (If you need YAML format)
restler/framework suggests installing twig/twig (If you want to use twig templates with Html format)
restler/framework suggests installing zendframework/zendamf (If you need AMF format)
Generating autoload files
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? 
```
> **Notes**: -  https://github.com/Luracast/Restler-Application has application starter templates for restler. Each branch contains a different template to choose. It is using https://github.com/Luracast/Restler-Framework which is the subtree split of the Restler Core (see Luracast/Restler)

## Tweaking

Command on the terminal:
```
atom explorer_test
```
changed the get method of Home class to post as shown below

```php
<?php

class Home
{
    public function post($name)
    {
        return array(
            'success' => array(
                'code' => 200,
                'message' => 'Restler is up and running!',
            ),
        );
    }
}
```

## Testing 

Command on the terminal:
```
cd explorer_test/
php serve
```

Result:
```
Web app development server started on http://localhost:8000
[Wed Feb  3 19:04:15 2016] ::1:59627 [403]: /
[Wed Feb  3 19:04:42 2016] ::1:59687 [400]: /
```

On the browser:

![explorer](https://cloud.githubusercontent.com/assets/2255137/12781239/138fd7fc-caae-11e5-9390-e93019474223.png)

**Comment by Arul-** [comment]
I know that restler-framework's rc6 is one commit behind luracast restler's rc6

I did copy that change and tried as well, with the same result as above!

**Comment by igorsantos07** [comment]
I'm probably using an outdated version of the Explorer, as your screenshot
shows, for instance, the datatype correctly. I'm going to merge the ideas
from that example into my project and see if it works.

Meanwhile: is that awesome example documented anywhere? It seems waaaay
simpler to introduce someone to Restler using it instead of the docs!
congratz!


*Igor Santos*
Desenvolvedor web / mobile
igorsantos.com.br <http://www.igorsantos.com.br>

**Comment by igorsantos07** [comment]
It seems I found the problem.
I tried updating to RC6 (I was using `^3.0` with dev stability, what
brought me `3.x-dev`), to no avail. Not even the datatype format changed, I
should note.

However, there's a rewrite rule in my Nginx that includes a trailing slash
in the end of all API methods; that's done, as it seems, using a `301
Moved`, but the JS used by the explorer do not follow the redirection
correctly: the original POST call becomes a GET one.

[image: Inline image 1]

Removing the rewrite rule makes the POST call work. I think this is a bug
in Explorer/Swagger, as 301 should be followed corretly... right?



*Igor Santos*
Desenvolvedor web / mobile
igorsantos.com.br <http://www.igorsantos.com.br>

**Comment by igorsantos07** [comment]
It seems I found the problem.
I tried updating to RC6 (I was using `^3.0` with dev stability, what brought me `3.x-dev`), to no avail. Not even the datatype format changed, I should note.

However, there's a rewrite rule in my Nginx that includes a trailing slash in the end of all API methods; that's done, as it seems, using a `301 Moved`, but the JS used by the explorer do not follow the redirection correctly: the original POST call becomes a GET one.

![screenshot_605](https://cloud.githubusercontent.com/assets/532299/12783916/4942963e-ca6b-11e5-8fed-9bee58272470.jpg)

Removing the rewrite rule makes the POST call work. I think this is a bug in Explorer/Swagger, as 301 should be followed correctly... right?

**Comment by Arul-** [comment]
> Meanwhile: is that awesome example documented anywhere? It seems waaaay
simpler to introduce someone to Restler using it instead of the docs!
congratz!

Thanks! we did share it via [twitter](https://twitter.com/Luracast) and [facebook](https://www.facebook.com/Luracast/) but your help will be appriciated in bringing it to the right places :+1:

**Comment by Arul-** [comment]
See if you can figure out if this is resolved in Swagger by using it against  `explorer/resources.json` once you confirm that it works, we can see how we can bring it back to Explorer

**Comment by igorsantos07** [comment]
Are the docs / examples open source as well? Is there any path to change
them you could point me to?

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by Arul-** [comment]
Thanks for taking the initiative

Example documentation is created by 

1. creating an example with prefix _ and 3 digit prefix followed by an _  (example:- _016_forms)
2. adding inline documentation in index.php (see https://github.com/Luracast/Restler/blob/master/public/examples/_016_forms/index.php)
3. extracting it as a markdown document readme.md (see https://github.com/Luracast/Restler/blob/master/public/examples/_016_forms/readme.md)
4. creating html with some templates to include navigation etc as readme.html (see http://restler3.luracast.com/examples/_016_forms/readme.html)

The build tool that does that is not open source yet! but I can share it with you

You can start by making pull request with more examples (example:- _017_composer)
