### ISSUE TITLE
Explorer default CSS file is too restrictive

### ISSUE THREAD

**Issue by igorsantos07** [Luracast/Restler#510]
I'm trying to use HTML to document a method but it's quite hard, given the current CSS rules in the Explorer.

In the samples, `<mark>` is used to display inline code, but in the current version it sports the default browser styling: a yellow marker.

I think the biggest suggestion here - and I'm not sure if it's doable given the page probably depends on it - would be to replace the `reset.css` by something more permissive and less destructive.

I mean destructive as we are unable to use lists, `i` or `em`, `kbd` or `code` as they all had their styling completely removed. Nothing gets italicized or monospaced! The only tag that I could use properly was `b`, and I had to uglily include inline CSS to make a list appear as a real list.

If that's not possible, the Plan B would be to include default styling for the "Implementation Notes" section, such as monospace for code tags (besides `pre`), and so on.

**Comment by Arul-** [comment]
Newer versions of explorer expose the CSS and HTML via dynamic loading, you may override them by placing the files in exact subpath inside public folder
