### ISSUE TITLE
Zend Opcache settings for comments

### ISSUE THREAD

**Issue by stevenbalthazor** [Luracast/Restler#511]
Does Restler have any requirement for the opcache.load_comments/save_comments to be set to 1?  

From my testing, Restler does not appear to be impacted by setting these two values to 0; however, I would think the annotations parsing which occurs would require these to be set to 1.  Am I missing something or is my testing faulty?

Can someone provide a definitive answer?

Thanks,
Steven Balthazor

**Comment by Arul-** [comment]
Sorry for the delayed reply!

`opcache.save_comments` needs to be `true` in order to parse the docblocks.

When running in production mode, all routes are created ahead of time and cached, so in that case it can be turned off safely as well for better performance
