### ISSUE TITLE
Setting UploadFormat Mime Types

### ISSUE THREAD

**Issue by ronnieserr** [Luracast/Restler#513]
Hi Arul,

I successful set Luracast\Restler\Format\UploadFormat $allowedMimeTypes to allow PDF uploads as well, e.g.

    public static $allowedMimeTypes = array('image/jpeg', 'image/png', 'application/pdf');

Is there a way to do it programmatically?

I'm afraid to forget to manually update it when updating/upgrading Restler.

Thanks,

Ronnie Serr

**Comment by Arul-** [comment]
I suggest you spend some time strengthening your PHP basics.

You are not supposed to edit the UploadFormat class manually

Just set this property in your index.php

```php
<?php
require_once '..vendor/restler.php';
use Luracast\Restler\Restler;
use Luracast\Restler\Format\UploadFormat;

UploadFormat::$allowedMimeTypes = array('image/jpeg', 'image/png', 'application/pdf');


$r = new Restler();
$r->addAPIClass('MyApiClass');

$r->handle();
```

**Comment by abides** [comment]
Is this possible for method specific or should i allow globally then handle in the method additionally?

**Comment by Arul-** [comment]
Up to Restler 5 to globally set it and handle it under the method

**Comment by abides** [comment]
I'm using "restler/framework": "5.0.9"
