### ISSUE TITLE
Could we make JsonFormat show an encoding error when an issue occurs.

### ISSUE THREAD

**Issue by kitsunde** [Luracast/Restler#516]
There's a large range of JSON encoding issues that can happen, but [`json_encode`](https://secure.php.net/manual/en/function.json-encode.php) will only return `false`. [`json_last_error`](https://secure.php.net/manual/en/json.constants.php) will have the actual error.

It's hard to understand at first why restler returns an empty response so it would be helpful if an encoding error of some kind was returned instead.

**Comment by Arul-** [comment]
It is already handled by https://github.com/Luracast/Restler/blob/master/vendor/Luracast/Restler/Format/JsonFormat.php

See the `handleJsonError` method
