### ISSUE TITLE
permission checks within an API endpoint

### ISSUE THREAD

**Issue by alexkb** [Luracast/Restler#517]
If I have an API endpoint that should behave differently depending on whether the client has certain permissions, is it acceptable to do this "Protection API" logic within the API endpoint function?

The alternative of this is having two or more API endpoints, one for the public, and another for those with a permission ([as per the docs](http://restler3.luracast.com/examples/_005_protected_api/readme.html)). This means, the client that uses this API has to make a decision about which endpoint to use based on the users permissions - which it will likely not be aware of. This use case is in a setup that uses JWT's, so the permission is included in the token and could be relied on.. but it kind of feels wrong..

This feels like a fairly standard use case, so maybe I've missed something in the documentation.

Lastly, thanks to Arul & Luracast for a great API server framework. Cheers.

**Comment by Arul-** [comment]
Take a look at access control example in http://restler3.luracast.com/examples/_010_access_control/readme.html

This uses user's role to determine which apis are accessible. Use that as an example to build your own based on user permissions. You can use JWT in your auth class implementation

**Comment by alexkb** [comment]
@Arul- I'm aware of those docs but it states that one endpoint exists for each role. What I'm asking is, can we have one endpoint that behaves differently based on different roles. Currently to do this, you have to wrap the calls to the endpoint server in the client, and assume the client can accurately work out which endpoint to use.

**Comment by RVN-BR** [comment]
I published our usage a while back... maybe you can find it still here... I'll check...

In my use, the class definition will include a variable for what "permissions" are required to access it.  

Then if I have different behaviors within the same function I check against the user permission on a core object that holds client/user information.

Perhaps a better way is a function that you pass to it the users "authenticated level" as well as a function for executing if the level is enough... and basically wrap that inside the endpoint...

some semi-pseudo code would look like (please dont try to run this its mostly moot to show a few concepts...:

Example A: change the logic inside the function based on permission
```php

/*
* @url GET /Things
*/
function getThings(){
   $UserPermission = \MyAuthenticationClass::getUserPermissions(); //could return a text, or array for example

   // change the query based on permission
   if ($UserPermission == "all") $MyQuery = "select * from Things"; 
   if ($UserPermission == "some") $MyQuery = "select * from Things Where LevelField = "some"";
  // this example is assuming only users with those two levels are allowed into the permission checker...

  return (MyDBClass::queryToArray($MyQuery));
}
```

Example B: an intermediate function chooses what to call
```php

/*
* @url GET /Things
*/
function authRouterThings(){
   // Define some sort of permission map where permission X calls function Y...
   $authMap = 
      ["all" => "allThings",
      "some" => "someThings"];
  return (\MyAuthenticationClass::routeUser($authMap));  // Call a function which has the user's authenticated permission, and calls the corresponding function... This routeUser function could include a default for no-matches for exaple, returning an Unauthorized, etc...
}
```

I hope this is somewhat clear? Sorry if it isnt... today we basically use method A for "permission tweaking"...  We dont let the user call the route at all if he doesnt have a permission, but sometimes there are compound permissions which play into game (for example he has the ViewUsers permission, and also a "Admin" permission... We adjust the function based on the second permission to baheave differently...)

In future we may adopt a router type function, but if its just for example adjusting if certain fields are visible or etc, it might not be worth it...

I'll try and find my auth example which uses doc comments to restrict access straight at the Restler authentication layer.

**Comment by RVN-BR** [comment]
FYI the discussions were in issue #3  and #149

**Comment by Arul-** [comment]
@RVN-BR :+1:
