### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by igorsantos07** [Luracast/Restler#521]
I've needed Restler for a small project in December and noticed a lot of rough edges (mainly in the Explorer). None got assigned, not even replied, here in the issues list. A month passed and I saw no improvements on that at all...

What's the current project state? Is there something specially difficult going on and you need some help? Got no time for it? Not using anymore?

**Comment by Arul-** [comment]
Restler is alive and kicking! We are using it everyday too!

Just got little tied up, will be responding to the issues and fixing them soon

**Comment by igorsantos07** [comment]
I guess it's used somewhere, indeed :)
But I got worried the issues were not even get replies explaining the
situation.

Good to know, though! If you need help, make it clear! I might be able to
join :)

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by Arul-** [comment]
> If you need help, make it clear! I might be able to
join :)

An extra pair of hands can surely help speedup things :+1:
