### ISSUE TITLE
[Explorer] Description and Data type mismatches on var requirement

### ISSUE THREAD

**Issue by igorsantos07** [Luracast/Restler#523]
As the given screenshot shows, an argument will not be shown as not-required in the "Description" field.
- at the first hand this is an issue since the info in the same line is repeated and mismatches;
- for me at least it's even worse as the DataType column is buggy and do not display details like in the sample application (I think I mentioned it before, it seems related to #461);
- finally, why the information is repeated? The "description"  column is supposed to contain a descriptive string istead of the field details?

**Comment by Arul-** [comment]
Please reopen if needed
