### ISSUE TITLE
[Explorer] Protected classes won't appear in Explorer?

### ISSUE THREAD

**Issue by igorsantos07** [Luracast/Restler#524]
I've stumbled upon some weird issues regarding protected methods and APIs. I'm using in the gateway file this snippet, what successfully displays the protected methods, except for some cases:

I have a class with only one public method, the rest being `protected` through PHP visibility mechanism. That public method is the first in the class, and everything appears fine in the Explorer. However, if I move the protected one down in the source, the class would disappear from the Explorer (?!).
In the same manner, when I created a new class and added `/** @access protected */` to its header, the entire class vanished from the Explorer. I tried to reproduce that in the sample app but had no success :( I'm using `"restler/framework": "3.0.0-RC6"`.

Here's how the code from the mixed class is organized. If I put `post()` together with `postIndex()`, the entire class will not appear in the Explorer anymore.
![screenshot_613](https://cloud.githubusercontent.com/assets/532299/12835626/08fd0e86-cb99-11e5-8174-181d6f6547c5.jpg)

**Comment by Arul-** [comment]
Explorer hides protected methods by default

Idea is to show documentation of what public methods that can be accessed directly

When you authenticate yourself and try explorer (it can be api key or your own login method) you should see those protected method listed

You can change this behavior by setting

```php
Explorer::$hideProtected = false;
```

in index.php

**Comment by igorsantos07** [comment]
Whoops. It seems I forgot to paste the snippet I mentioned. Anyways, the reported issue happens with the piece of code you said.

**Comment by Arul-** [comment]
Share some code to reproduce it! I will take a look

**Comment by igorsantos07** [comment]
AHA! [Found it](https://gist.github.com/igorsantos07/2f0720c977e4b7478b36).
The items disappear from the Explorer as described when there's no authentication - in this case, there's no auth Cookie. If I login in my app the items appear as expected.
I guess this is a conflict between the auth method I decided to use and the Explorer's one? Anyway, I expected those type of issues to be bypassed by the docs at least, when using `$hideProtected = false`.

**Comment by Arul-** [comment]
I could see the protected api with your code

See the image below!
![screen shot 2016-02-20 at 9 30 50 pm](https://cloud.githubusercontent.com/assets/2255137/13196944/47cbf9b0-d819-11e5-8d5f-2cb6d3552b38.png)

Here is what I did,

I created a new application with

```bash
composer create-project restler/application:dev-basic exporer-test
```
Overwrote the index.php in public folder with yours and added Session class to src folder

```php
<?php //index.php

use Luracast\Restler\Restler;
use Luracast\Restler\Explorer;

require __DIR__ . '/../vendor/autoload.php';


$r =  new Restler();

$r->addAPIClass('Home','');
$r->addAPIClass('Explorer');
//$r->addAuthenticationClass('Session');
$r->addAPIClass('Session');
Explorer::$hideProtected = false;

$r->handle();
```

```php
<?php 

use Luracast\Restler\iAuthenticate;
use Luracast\Restler\RestException;

class Session implements iAuthenticate {

    /**
     * Points the basic user level needed whenever authentication is used.
     * Can be changed by API method using "@class Session {@requires manager}"
     * @var int
     */
    public static $requires = 1; //was a constant

    /**
     * The level of the current authenticated user
     * @var int
     */
    public static $currentLevel = 0;

    const SESSION_NAME = 'token';

    protected static function _sessionStart() {
        if (session_status() == PHP_SESSION_ACTIVE) {
            return;
        }

        //protecting against badly-cleaned cookies
        if (isset($_COOKIE[static::SESSION_NAME]) && !$_COOKIE[static::SESSION_NAME]) {
            unset($_COOKIE[static::SESSION_NAME]);
        }

        session_name(static::SESSION_NAME);
        session_set_cookie_params(0, '/', null, isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'], true);

        if (isset($_SERVER['HTTP_AUTHORIZATION'])) {
            if (stripos($_SERVER['HTTP_AUTHORIZATION'], 'Bearer ') === 0) {
                $parts = explode(' ', $_SERVER['HTTP_AUTHORIZATION']);
                if (isset($parts[1])) {
                    session_id($token = $parts[1]);
                }
            }

            if (!isset($token)) { //if the header was sent but no token was found, the request was badly formed
                throw new RestException(HTTP_BAD_REQUEST, 'Incomplete auth header');
            }
        }
        session_start();
    }

    protected static function _gotSessionData() {
        return isset($_COOKIE[static::SESSION_NAME]) || isset($_SERVER['HTTP_AUTHORIZATION']);
    }

    public function __getWWWAuthenticateString() {
        return 'POST /session { email, password }';
    }

    /**
     * Access verification method.
     * API access will be denied when this method returns false
     * @return boolean true when api access is allowed false otherwise
     * @throws 403 Forbidden User level is not enough
     */
    public function __isAllowed() {
        if (!self::_gotSessionData()) { //sent no session token, so there's no reason to even open it
            return false;
        }

        static::_sessionStart();

        if (!(isset($_SESSION['email']) && $_SESSION['email'])) { //not authenticated!
            $this->delete();
            return false;
        } else { //authenticated, who are you?
            static::$currentLevel = $_SESSION['level']?: 0;

            $allowed = [static::$requires, User::LEVELS[static::$requires], User::LVL_MANAGER];
            if (in_array(static::$currentLevel, $allowed)) {
                return true; //nice badge you got there, go ahead
            } else {
                throw new RestException(HTTP_FORBIDDEN); //you're not allowed to be here, move on
            }
        }
    }

    /**
     * Authenticates a user and issues a session cookie.
     * If the client does not support cookies, the behaviour can be easily simulated by
     * storing the cookie name and value (got from the Set-Cookie header) and sending
     * it back with a "Cookie" header.
     * @param string $email
     * @param string $password
     * @throws 401 Unauthorized
     * @return array The auth token, also contained in the Set-Cookie header.
     */
    public function post($email, $password) {
        User::$throwOnFind = false; //so we won't disclose what users are valid
        /** @var User $user */
        $user = User::where('email', $email)->first();
        if ($user && User::$hasher->check($password, $user->password)) {
            static::_sessionStart();
            session_regenerate_id();

            $result = ['token' => session_id()];
            foreach($user->attributesToArray() as $field => $value) {
                $_SESSION[$field] = $result[$field] = $value;
            }
            return $result;
        } else {
            $this->delete();
            throw new RestException(HTTP_UNAUTHORIZED);
        }
    }

    /**
     * Destroys the user session.
     * @status 204
     */
    protected function delete() {
        static::_sessionStart();
        setcookie(static::SESSION_NAME, null, null, '/');
        $_SESSION = [];
        session_destroy();
    }
}
```

**Comment by igorsantos07** [comment]
I'm sorry for taking forever to reply to such a stupid mistake, but the Gist I had posted was wrong.

As the issue is with the Authentication procedure, the related line in `index.php` should be uncommented:

> $r->addAuthenticationClass('Session');

This way, having no auth will block showing protected methods in the explorer.

**Comment by Arul-** [comment]
Ok will check that out!, by the way there is some progress on swagger2 spec in `features/swagger2.0` branch. Check that out!

**Comment by engharb** [comment]
Hello,

I tried to call Luracast\Restler\Explorer class in my app.php as:
```$r->addAPIClass('Luracast\\Restler\\Explorer'); //this creates resources.json at API Root```

But it could not find this class and is no exist in vendor/Luracast/ ? 

Any suggestion how to fix that?

regards,

**Comment by Arul-** [comment]
@engharb see the reply in https://github.com/Luracast/Restler/issues/563#issuecomment-356314394 

Please do not post same question in multiple places
