### ISSUE TITLE
[Suggestion] Replace param validators with Illuminate\Validation

### ISSUE THREAD

**Issue by igorsantos07** [Luracast/Restler#527]
First of all, I must say the validation mechanism is simply awesome, having it built in the natural coding we already have (documented). However, it's a little bit limited. For instance, I had no way to validate timestamps in the ISO-8601 standard (common for APIs), nor times (without using hard-to-read patterns). Also, sometimes more complex validation must be made inside the methods, or by separate blocks of code.

My suggestion is to import the [validation library from the Laravel framework](https://laravel.com/docs/5.2/validation#available-validation-rules), that already comes packed with lots of validators. It's easy to be used outside of the framework and comes with very few, light [dependencies](https://packagist.org/packages/illuminate/validation).

What do you think? I might hop on the board to implement this in a PR.

**Comment by Arul-** [comment]
We can easily improve validator. Take a look at https://github.com/Luracast/Restler/blob/master/vendor/Luracast/Restler/Data/Validator.php

Just adding a static method here gives you yet another validation! just make pull requests to v3 branch for ISO-8601 etc

Also validator supports custom method validation too! see https://github.com/Luracast/Restler/blob/master/vendor/Luracast/Restler/Data/Validator.php#L376

you can define `{@method myMethod}` to validate against a method in api class

By digging through the source code you will find lot of hidden gems that needs to be documented!

**Comment by Arul-** [comment]
by the way we can use our own validator class by implementing iValidate and then use them instead

```php
Defaults::$validatorClass = 'MyCustomValidator';
```

**Comment by igorsantos07** [comment]
One more thing that's not documented. Haha
How about creating a label "needs doc" for all those issues?
If you do so, please reopen those :)
