### ISSUE TITLE
Swagger 2.0 RC6

### ISSUE THREAD

**Issue by letsbyteit** [Luracast/Restler#529]
Hey guy!

I've got struggle trying to get Restler to generate Swagger 2.0 output. There is a feature branch and it brings the `Explorer.php` that replaces `Resources.php`. I've upgraded my project to RC6 to make it compatible, but I don't even get the examples working.

The problem is: Every time I call a resources.json in an example, I get the 404:

```
{
    "error": {
        "code": 404,
        "message": "Not Found"
    },
    "debug": {
        "source": "Routes.php:458 at route stage",
        "stages": {
            "success": [
                "get"
            ],
            "failure": [
                "route",
                "negotiate",
                "message"
            ]
        }
    }
}
````

This is the `index.html` from the example you're referring:
![screen shot 2016-03-08 at 02 32 24](https://cloud.githubusercontent.com/assets/7833199/13589166/1fcaf6ea-e4d6-11e5-92ae-6a0e22e40d86.png)

My project is doing even more interesting things: It still outputs Swagger 1.1.
Also, I'm seeing some JS-errors:
![screen shot 2016-03-08 at 02 29 37](https://cloud.githubusercontent.com/assets/7833199/13589141/e50caca6-e4d5-11e5-8058-806e22ff4ed9.png)

Of course, I replaced 
````
$restler->addAPIClass( "\Luracast\Restler\Resources" );
````
with
````
$restler->addAPIClass( "\Luracast\Restler\Explorer" );
````
as you've done it in the example.

It took me some hours to review all the commits and compare things… maybe I'm just overlooking something obvious?

I think, it would be a great time to sum up the current status on the Swagger 2.0 implementation and what still needs to be done. Also, a simple example - that's actually working - should be documented.

**UPDATE:** I replaced the Restler-Vendor files from the Feature branch with the RC6 master files. Now, I also get the 404 in my own project.

**Comment by Arul-** [comment]
swagger 2 support is only available in features/swagger2.0 branch. feature branches are experimental and can be incomplete. Anyway we did some changes today, it is still Work in Progress

But you can see some result now, tested with the rate limiting example!

If you are interested in contributing to swagger 2 integration, please let me know!

**Comment by letsbyteit** [comment]
@Arul- Ok, thank you. I've reverted my project to RC6. I tried your implementation from the latest commits in the feature-branch but didn't have any luck so far. I'm going to test in in detail, if I've got some spare-time the next days.
Yes, I'm interested in it. Currently, I've no real knowledge about swagger, but I really like Restler and I've gone through many of your commits to understand the implementation. So, if you like to introduce me a bit and tell me about the progress, I could try to help.

**Comment by Arul-** [comment]
@letsbyteit :+1:  Will keep you updated!

**Comment by Arul-** [comment]
http://swagger.io/specification/ gives the spec on expected JSON. We need to generate it from Restler api methods and the comments

Explorer was previously targeting swagger 1.2 spec, now we are trying to make it work for 2.0 spec

Checkout the latest version on features/swagger2.0 branch and go to the explorer in rate limiting example

You will see

![screen shot 2016-03-08 at 9 42 48 pm](https://cloud.githubusercontent.com/assets/2255137/13603248/bcb7d0ea-e576-11e5-8111-0e6b9f190bb5.png)
