### ISSUE TITLE
PHP7 json_decode on empty string

### ISSUE THREAD

**Issue by tomahock** [Luracast/Restler#536]
Hi,
PHP7 throws an error when json decoding an empty string. That didn't happened on PHP5.

Example:
``` php
<?php

$str = "";
var_dump(json_decode($str));
var_dump(json_last_error_msg());
```

PHP5
```
$ php -v
PHP 5.5.16 (cli) (built: Sep 15 2014 15:16:17)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

$ php str.php
NULL
string(8) "No error"
```

PHP7
```
$  php -v
PHP 7.0.4 (cli) (built: Mar 22 2016 19:30:45) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

$ php str.php
NULL
string(12) "Syntax error"
``` 

I think this can be handled in JsonFormat.php checking if the string is empty.
If you agree with this solution i can do it and pull request it.

Waiting for your feedback!

Thanks

**Comment by Arul-** [comment]
@tomahock :+1: agreed! make a pull request against the v3 branch, It will be included later in RC6 release
