### ISSUE TITLE
How to integrate a Restler Api package into Laravel 5 and use with eloquent.

### ISSUE THREAD

**Issue by zalasid** [Luracast/Restler#539]
I have try to integrate a Restler 3 with Laravel 5 using [luracast/restler](https://packagist.org/packages/luracast/restler) but I am stuck how to use Laravel DB and eloquent with Restler. Please help me or give reference links. Thanks.

**Comment by Arul-** [comment]
We don't have integration for Laravel 5 database, but we have one for Laravel 4.2

See https://github.com/Luracast/Restler-Application/tree/eloquent
