### ISSUE TITLE
Warnings when using multipe @param types

### ISSUE THREAD

**Issue by fabianbadoi** [Luracast/Restler#540]
Warning: substr() expects parameter 1 to be string, array given in .../vendor/Luracast/restler/vendor/Luracast/Restler/Data/Text.php on line 63

This happens when parsing `@var bool|string|callable` from Luracast\Restler\Data\Object because CommentParser:508 doesn't take into account $r['type'] being an array.

I've tested this on the v3.x-dev with php7 and had `$r->addAPIClass(\Luracast\Restler\Resources::class);`.

**Comment by Arul-** [comment]
Please share the minimal example to re-produce this

**Comment by fabianbadoi** [comment]
I was wrong when I said it was because of Luracast\Restler\Data\Object, my code just `Object` instead of `object` somewhere, but the warnings still appear when parameters can be of multiple types.

Start the server `php -S localhost:3003 index.php`.
[restler-issue-540.zip](https://github.com/Luracast/Restler/files/225458/restler-issue-540.zip)

**Comment by Arul-** [comment]
@fabianbadoi thanks for the sample, we could see the issue! we will resolve it ASAP

**Comment by fabianbadoi** [comment]
Thanks for the fix!

**Comment by Arul-** [comment]
You are welcome :)
