### ISSUE TITLE
Extending restler to override handle method

### ISSUE THREAD

**Issue by codemonkeyneo** [Luracast/Restler#549]
I am trying to override the handle method in Restler.

I have a class that extends Restler

```
class MyClass extends Restler {
```

My code uses MyClass as the Restler Server instance and all seems fine. I then try to add the 'handle;  method, which in theory should then be used by MyClass.

But I just get an uncaught exception error

```
Uncaught exception 'Luracast\Restler\RestException' ' in file Routes.php on line 458
```

Stepping through it doesnt go to my handle method so If i remove it it goes back to the Restler original and works. I'm extending the class so that I dont change the original source as its better to extend and will help with future updates.

Anyone have ideas on what I may be doing wrong.?

Cheers

**Comment by Arul-** [comment]
Does your class have a constructor?

**Comment by codemonkeyneo** [comment]
I have tried it with and without a constructor. I get same error. I removed constructor as I wasn't doing anything extra and was just calling the Parent:: one.

**Comment by Arul-** [comment]
You may try again with Restler 5 and reopen this if required
