### ISSUE TITLE
File upload in restler api explorer

### ISSUE THREAD

**Issue by patelbhoomika** [Luracast/Restler#550]
Browse button not display for file upload in post method in `luracast restler v3` API explorer.

I was follw **

> https://github.com/Luracast/Restler/issues/436#issuecomment-94357209

*\* this link for file upload in `luracast restler v3`.

In my post method not display browse button for file upload.

in my case show like  **[click here to show problem image](http://i.stack.imgur.com/JkQ9P.png)**

plz help

**Comment by mmihalev** [comment]
I have exactly the same problem!

**Comment by Arul-** [comment]
Explorer does not support file upload yet! hope to get it with swagger 2 spec and above

**Comment by mmihalev** [comment]
Good to hear that we will have this option. It's very needed for completing our project which is build on top of Luracast Restler.

**Comment by kaizirlewagen** [comment]
I tried several ways to get file upload working. But I don't get a file input field. Has someone a working example for this?

`    /**
     * Upload a test document
     *
     * Upload a test document
     * 
     * @status 201
     *
     * @param string $file {@field file} {@from body}
     * 
     * @format JsonFormat, UploadFormat
     * 
     * @throws RestException 400
     * @throws RestException 401
     * @throws RestException 404
     * 
     *
     */  
    function postUploadTest( $file ) {
    	return $file;
    }`

**Comment by Arul-** [comment]
File upload is not working in Explorer yet! but you can follow #436 to see how to get  file upload working with restler

**Comment by kaizirlewagen** [comment]
I switch to Swagger-UI (https://github.com/swagger-api/swagger-ui) in hope to get file upload working. But with my class i don't have a file choose button.

Do you know what can be wrong?

**Comment by kaizirlewagen** [comment]
I can't get an file input field working with restler and swagger-ui.

It is possible to get something like this:

![swagger-ui-file-upload](https://user-images.githubusercontent.com/8393808/100082259-4f6d0580-2e48-11eb-90d9-912347279e40.png)

Has someoen an idea for me?

**Comment by kaizirlewagen** [comment]
Sorry, i see ... Eplorer does not support this. Sorry for the repost.

**Comment by Arul-** [comment]
It is planned for Restler 6
