### ISSUE TITLE
PHP version vs Callable

### ISSUE THREAD

**Issue by vircom** [Luracast/Restler#558]
Composer requirements of PHP version are described like below:

> "require":{`
>       "php":">=5.3.0"
> },

But in file  Restler/vendor/Luracast/Restler/Scope.php we have:
`public static function register($name, Callable $function, $singleton = true)`

Callable is part of PHP 5.4 and above.
So i think you should change requirements of this package or try to use Clousure.

**Comment by Arul-** [comment]
You are right, we have updated the requirement in Restler 5 (formally RC6)
