### ISSUE TITLE
Explorer will only show version 1

### ISSUE THREAD

**Issue by grosch** [Luracast/Restler#563]
May API has v1 and v2, but when I go to .../v2/explorer it reverts back to the v1 API and doesn't show what's in v2.

**Comment by grosch** [comment]
Any thoughts here?  This is a big issue for API exploration.

**Comment by Arul-** [comment]
Sounds like a bug, which version are you trying?

**Comment by grosch** [comment]
It's working a little better now, but I'm still hitting some issues.  I'm using 3.0.0-RC6 of Restler. 

I've got two versions of my API right now.  In the 'src' dir I have v1 and v2 subdirs, and then the files in those directories each have a 'namespace v1;' or 'namespace v2';

I can hit either one via these URLs:

* https://_domain.name._/v1/_apiClass_/...
* https://_domain.name._/v2/_apiClass_/...

When I go to the explorer any parameter to a function which is part of the body (like from a POST) is not listing the type, it's listing a made up model name.

For example, one of my methods has a header which includes lines like so:


    * @param int    $id               The sql_ident of the Person to update {@from path}   
    * @param string $email            The new email {@type string}


There are about 15 of them that come from the body.  The first one lists in the explorer properly (it comes from path), and all the rest are grouped together and just say v2\PersonModel8

This is what my index.php looks like.  Not entirely sure about that setAPIVersion(2) but without it nothing works.

```php
<?php

declare(strict_types = 1);

use Luracast\Restler\Defaults;
use Luracast\Restler\Format\JsonFormat;
use Luracast\Restler\Restler;

require __DIR__ . '/../vendor/autoload.php';

set_include_path(get_include_path() . PATH_SEPARATOR . '/var/www/api/src');

JsonFormat::$numbersAsNumbers = true;
Defaults::$useUrlBasedVersioning = true;

ob_start();

$r = new Restler();
$r->setAPIVersion(2);

$r->onComplete(function () use ($r) {
    $buffer = ob_get_contents();
    ob_end_clean();

    if (array_key_exists('HTTP_ACCEPT_ENCODING', $_SERVER) && strpos($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip') !== false) {
        header('Content-Encoding: gzip');
        $buffer = gzencode($buffer, 9);
    }

    header('Content-Length: ' . strlen($buffer));

    die($buffer);
});

$r->addAPIClass('Explorer');
$r->addAPIClass('Person');
$r->addAPIClass('Team');
$r->addAPIClass('Conversation');
$r->addAPIClass('Calendar');
$r->addAPIClass('Performances');
$r->addAPIClass('Sponsor');
$r->addAPIClass('Todo');
$r->addAPIClass('News');
$r->addAPIClass('StripeApi');
$r->addAPIClass('Task');

$r->handle();
```

**Comment by grosch** [comment]
Is there some way to get the property descriptions to show up?

**Comment by engharb** [comment]
How about 
```$r->addAPIClass('Luracast\\Restler\\Explorer'); //this creates resources.json at API Root```

I have added this line to symfony3 web/app.php, but the Explorer is not found under vendor/Luracast.

Before update my project this class was Explorer.php there but later on by reinstalling restler this class is no longer found.?

Any suggestion?

Thanks

**Comment by Arul-** [comment]
Now there are two explorer classes in RC6

1. https://github.com/Luracast/Restler/blob/v3/vendor/Luracast/Restler/Explorer/v1/Explorer.php
2. https://github.com/Luracast/Restler/blob/v3/vendor/Luracast/Restler/Explorer/v2/Explorer.php

first one, supporting the swagger 1.2 spec and second, supporting swagger 2 spec

if you have used `$r->addAPIClass('Explorer');` you will get Explorer 2

More info on the commit message in 9ca6dadb5f17e6dedccc3087957c8e2e25bd6cf8
