### ISSUE TITLE
specify php7 incompatibilities in composer 

### ISSUE THREAD

**Issue by jeff1985** [Luracast/Restler#566]
The 3.0.0 version is currently not php7 compatible. You can easily verify that by running: `vendor/luracast$ find . -type f -name "*.php" -exec php -l {} \; | grep -v 'No syntax errors'` 

For 3.0.0 version from composer the command shows:

    Fatal error: Cannot use Luracast\Restler\Data\String as String because 'String' is a special class name in ./restler/features/bootstrap/RestContext.php on line 4
    Errors parsing ./restler/features/bootstrap/RestContext.php
    Warning: The use statement with non-compound name 'PDO' has no effect in ./restler/public/examples/_007_crud/DB/PDO/Sqlite.php on line 9
    Fatal error: Cannot use 'String' as class name as it is reserved in ./restler/vendor/Luracast/Restler/Data/String.php on line 14
    Errors parsing ./restler/vendor/Luracast/Restler/Data/String.php
    Fatal error: Cannot use Luracast\Restler\Data\String as String because 'String' is a special class name in ./restler/vendor/Luracast/Restler/Resources.php on line 4
    Errors parsing ./restler/vendor/Luracast/Restler/Resources.php
    Fatal error: Cannot use Luracast\Restler\Data\String as String because 'String' is a special class name in ./restler/vendor/Luracast/Restler/Routes.php on line 5
    Errors parsing ./restler/vendor/Luracast/Restler/Routes.php
    Fatal error: Cannot use Luracast\Restler\Data\String as String because 'String' is a special class name in ./restler/vendor/Luracast/Restler/UI/Forms.php on line 6
    Errors parsing ./restler/vendor/Luracast/Restler/UI/Forms.php

I also have seen, that you denied to accept a pull request fixing compatibility issues in the master branch. As specified [here](https://github.com/Luracast/Restler/pull/534), the problems have been resolved only in RC6 branch. Please also note, that this pull request is now 6 months old. So it seems clear to me, that you've chosen currently not to support php7 in the master branch.  

Currently [packagist](https://packagist.org/packages/luracast/restler#3.0.0) does not show any maximum php version requirements. Please specify the maximum php version in branches before RC6 to allow composer to output a compatibility warning when trying to install i.e. 3.0.0 on a system running php7.

**Comment by Arul-** [comment]
Agreed 👍  Thanks for contributing to Restler!

**Comment by Arul-** [comment]
On a second thought decided to make it compatible with PHP 7 instead

See 581d8d6dc5d37f439765f89725a92f85e98f1826

**Comment by jhfrintrop** [comment]
Please update https://github.com/Luracast/Restler-Framework

**Comment by Arul-** [comment]
@jhfrintrop Done! Sorry for the delay
