### ISSUE TITLE
No syntax errors in apache error log...

### ISSUE THREAD

**Issue by marcolino** [Luracast/Restler#573]
I'm experiencing this issue:

When I have an error (for example a syntax error) in one of my classes (a class I add to my restler instance with addAPIClass() method in index.php), I do not get any evidence of it in my apache2 error log.

Instead, I correctly get errors - for example - from index.php or from AccessControl.php (which is not added to my restler instance with addAPIClass() but with addAuthenticationClass().

I correctly get messages from error_log() called from any of my classes.

Any suggestion? It's a real pain to debug classes producing say an error 500 without any clue in the log file... :-(

**Comment by Arul-** [comment]
Sounds weird and looks like a `php.ini` config issue.  If its a development machine, configure PHP to show errors

https://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display
