### ISSUE TITLE
real world example

### ISSUE THREAD

**Issue by alzalabany** [Luracast/Restler#583]
the example list is great, but not enough to cover all tips and tricks of the framework.

is there is a list of open source projects built with luracst/restler or a single realworld example that show advanced stuff slike

caching, managing response status code, extending framework classes, access and uses of $this->restler this can be of a great help and addition to success of this great framework !

**Comment by yannis-rossetto** [comment]
Hello,

We are using Restler for our REST Api in the [Tuleap](https://www.tuleap.org) project.
For the source code, you can found it [here](https://tuleap.net/plugins/git/tuleap/tuleap/stable?p=tuleap%2Fstable.git&a=tree&h=e789479de8dc8325d8bf1f6658036f8a79316788&hb=15363cdb11a0cbe2c1aaf8036158f362d4f1cafc&f=src/common/REST) or in our [Github mirror](https://github.com/Enalean/tuleap/tree/master/src/common/REST)

For other information, we are based on version 3 RC6 with some extra code for the authentication part, and we are checking for upgrade Restler to a more earlier version.

**Comment by Arul-** [comment]
We have created https://github.com/Luracast/Restler/wiki/Restler-API-listing so that anyone can showcase their api created with restler.  @yannis-rossetto please add Tuleap there!

**Comment by yannis-rossetto** [comment]
@Arul- Done.

**Comment by Arul-** [comment]
I have updated it to add source code url as well

**Comment by Arul-** [comment]
I will close this issue for now!
