### ISSUE TITLE
Directory traversal vulnerability in Restler Explorer

### ISSUE THREAD

**Issue by jeff1985** [Luracast/Restler#584]
**Restler Explorer**
3.0.0-RC6 introduced the Luracast\Restler\Explorer class to simplify the usage of Restler Explorer. Thanks for that! To activate this new feature, i had to add the apropriate class to my Restler setup:
`$r->addAPIClass('Luracast\\Restler\\Explorer');`

**Security vulnerability**
I've been experimenting with this new class and found that the $filename parameter is not sanitized:
`PassThrough::file(__DIR__ . '/explorer/' . (empty($filename) ? 'index.html' : $filename), false, 0);`

This allows an attacker to read arbitrary files via ..\ sequences in the $filename parameter!

**Example**
`curl -v --path-as-is "http://myproject/api/explorer/../Defaults.php"` 

This shows me the contents of Luracast\Restler\Defaults class. 

**Limitations**
On my system(Homestead VM, Nginx), I'm only able to read the contents of the vendor/luracast/restler/vendor/Luracast/Restler/ directory and any directory above that, i.e. Restler/Data. When I try to dig deeper with `../../` I get a "400 Bad Request". This limits the practical usage of this vulnerability, because the Restler code is on github anyways and I can not get to the website code directory. I did not test the problem on apache, but it could be different depending on config and project directory structure.

**Comment by Arul-** [comment]
Fixed in dd220ec6bdf43cf967b94a386fabbfe5010f9d9b
