### ISSUE TITLE
About the Error 500 sendin json

### ISSUE THREAD

**Issue by Chetan-citrusbug** [Luracast/Restler#586]
I am using restler api with swagger ui. I am send json then getting 500 error. I dont know why it some time working or not some time.
I am attaching json and the screenshot which i am getting.
Please help guys
[500 error.zip](https://github.com/Luracast/Restler/files/1219561/500.error.zip)

**Comment by Arul-** [comment]
Use the chrome developer tools to see the exact response, it contains all the clue needed on what's wrong

**Comment by Chetan-citrusbug** [comment]
i tried using chrome developer tool but it's give me this error
: http://prntscr.com/g8m00v

**Comment by gulerof** [comment]
don't use this framework. it's abandoned and his devs are ignoring all PR

**Comment by Arul-** [comment]
you need to see the exact output using chrome tools. Use google to find out how
