### ISSUE TITLE
for array definition @max is applied to int values

### ISSUE THREAD

**Issue by magarnier** [Luracast/Restler#587]
Hi,

I have a strange behavior on C6:

If I set the following instruction
@param array {@max 10} {@type int}
the at max will be applied on the value of elements inside the array (value:[15,20] will be invalid)

If I set 
@param array {@max 10} 
the at max will be applied on array size.

Is there a way to do the validation I want?

**Comment by gulerof** [comment]
don't use this framework. it's abandoned and his devs are ignoring all PR

**Comment by Arul-** [comment]
@gulerof if you can help someone solve the issue do so, how does this help?

**Comment by Arul-** [comment]
It should work as you expect. Let me fix this bug!

**Comment by Arul-** [comment]
Fixed on above commit which will soon be RC6
