### ISSUE TITLE
Automatic invalidation of web/cache/

### ISSUE THREAD

**Issue by lathspell** [Luracast/Restler#589]
The documentation suggests to activate the Restler "_production mode_" in production environments. The drawback though is that apparently one has to remove the `web/cache/` directory manually as Restler does not pick up new URLs otherwise. This sounds like a big source of problems where people fix their code, update it on the production server and then do not realize that the new method is still not available.

Sugestions to improve this:
1. Make usage of cache independent from whatever else "production mode" does so that one can turn it of with e.g. `$restler->setUseCache(false).`. Maybe even disable it by default.
2. Invalidate the cache when the "last modified" timestamp on index.php or one of the API classes is more recent than that of the cached routes.php

**Comment by lathspell** [comment]
Browsing the source code I see the `$refreshCache` argument in the constructor of Restler.
Maybe at least add that parameter as 'true' to the "7. Start Production" example for those who just copy and paste the example code.

**Comment by Arul-** [comment]
Agreed this is a problem to be addressed, at least in the documentation!

**Comment by Arul-** [comment]
Documented in 4b26b12d4d511994060db461b7fcea36234d1a00
