### ISSUE TITLE
Restler not compatible with PHP 7.2

### ISSUE THREAD

**Issue by eldy** [Luracast/Restler#591]
When using library with php 7.2, we get this error

<b>Fatal error</b>:  Cannot use Luracast\\Restler\\Data\\Object as Object because \'Object\' is a special class name in <b>/home/travis/build/Dolibarr/dolibarr/htdocs/includes/restler/framework/Luracast/Restler/Format/JsonFormat.php</b> on line <b>4</b><br />

The class Object is now reserver in PHP 7.2. Please rename it into ObjectRestler or something else...

**Comment by Arul-** [comment]
Object class is now renamed as Obj

**Comment by eldy** [comment]
Thanks. However there is a pb during the merge into branch 3.0.
The file Obj.php was saved into dir   restler/Data  with a r lowercase when it should be into
Restler/Data with other classes. Also file Restler/Data/Object.class.php can be removed.

**Comment by Arul-** [comment]
> is it done on purpose ?

Nope!

In the repository they seem fine, see https://github.com/Luracast/Restler/tree/097608f0772ca42f2858820e8886533a3cb99232/vendor/Luracast/Restler/Data

Try deleting Luracast folder and do `composer install` to bring the new one

**Comment by infabo** [comment]
What happend here? In v3 there is a static property $resolver, which is not present in master

https://github.com/Luracast/Restler/blob/v3/vendor/Luracast/Restler/Scope.php

vs

https://github.com/Luracast/Restler/blob/master/vendor/Luracast/Restler/Scope.php

**Comment by Arul-** [comment]
v3 contains the newest version

**Comment by infabo** [comment]
@Arul- Thanks!
