### ISSUE TITLE
Explorer class error generating swagger.json

### ISSUE THREAD

**Issue by mzangari** [Luracast/Restler#594]
I'm trying the swagger 2 compatible version of Explorer class from the features/swagger2.0 branch and found that at line 183 of Explorer.php class, in the swagger function, the following line of code fails 
`$r->basePath = $info['path']`
since unfortunately $info["path"] seems to be always null.
This happens at least in my (local) environment (and so the resource explorer fails to render).
As far as testing purpose, i just fixed locally adding this simple check:
`$r->basePath = !empty($info['path']) ? $info["path"] : $info["scheme"]."://".$info["host"];`

**Comment by Arul-** [comment]
Swagger 2 functionality is rewritten in the v3 branch, please try that instead and let us know if the problem still exists
