### ISSUE TITLE
How to setup versioning correctly?

### ISSUE THREAD

**Issue by Nico7an** [Luracast/Restler#595]
I want to try the versioning feature of Restler, but I think I’m doing something wrong.

I followed these steps:

```
use Luracast\Restler\Defaults;
use Luracast\Restler\Restler;
Defaults::$useUrlBasedVersioning = true;
$r = new Restler();
$r->setAPIVersion(2);

```
Then I put **namespace v1;** in each files of the v1 folder and **namespace v2;** for the v2 folder.

Then now I’m getting a notice when calling any route to version 2 only:

```
Undefined offset: 2 in Luracast/Restler/Restler.php on line 614
And an Allowed memory size error Luracast/Restler/AutoLoader.php on line 326
```

Thanks for any help :)

**Comment by Arul-** [comment]
Are you using RC5 or RC6?

**Comment by Nico7an** [comment]
RC5

**Comment by Arul-** [comment]
I just tried the RC5 versioning example on my localhost

I tried with both Luracast's autoloader and then composer's autoloader (by running `composer install` to get the dependencies)

I suggest you try the example first, ideally with composer autoloader
