### ISSUE TITLE
Option to turn off @param validation

### ISSUE THREAD

**Issue by daemionfox** [Luracast/Restler#597]
We keep getting caught by Restler's auto-validation of param types (our IDE frequently inserts a param type of null as default, causing Restler to reject any non-null params), is there a way to disable this feature, if not, can one be added?

**Comment by Arul-** [comment]
```php
use Luracast\Restler\Restler;
use Luracast\Restler\Defaults;

Defaults::$autoValidationEnabled = false;
```
This turns off the validation altogether. 

Ideally, restler should be able to ignore only null values.  Will work on that further!
