### ISSUE TITLE
Make Explorer show only specific methods

### ISSUE THREAD

**Issue by pkollitsch** [Luracast/Restler#600]
My Explorer shows all (public?) methods in my classes. Is there a way to tell Restler to only show methods that specifically have the @url doc-code defined? Auto routing to true - `Defaults::$smartAutoRouting = true;` - already shows less items in the list, but keeps exposing all public methods somehow.

**Comment by Arul-** [comment]
There is no specific way to hide auto-routed URLs, you can either turn off `smartAutoRouting` or hide the APIs from explorer using `Resources::$excludedPaths` or `Explorer::$excludedPaths` depending on which one you use.

It takes an array and all paths beginning with any of the items in that array will be excluded from documentation

**Comment by devbazilio** [comment]
Another way to hide some functions in class and not all routes in a class:
you need to create custom Resource class and remove original one from bootstrap core:

```
//index.php
$r = new Luracast\Restler\Restler($production);
$r->addAPIClass(MyResources, 'resources');
```

```
//MyResources.php
class MyResources extends \Luracast\Restler\Resources
{
    protected function verifyAccess($route)
    {
        if (isset($route['metadata']['hide-me'])) {
            return false;
        }
        return parent::verifyAccess($route);
    }
}

```

if you add "@hide-me" to function header , the function will not visible in Explorer

**Comment by Arul-** [comment]
@devbazilio It will be a surprise if `@hide-me` works! We did not add such a feature!
