### ISSUE TITLE
A list of suggestion when installing

### ISSUE THREAD

**Issue by commentatorboy** [Luracast/Restler#602]
I saw a list of projects, that are suggesing to install additional packages.

> symfony/translation suggests installing psr/log-implementation (To use logging capability in translator)
> symfony/event-dispatcher suggests installing symfony/http-kernel
> symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
> symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
> symfony/console suggests installing psr/log-implementation (For using the console logger)
> symfony/console suggests installing symfony/process
> behat/behat suggests installing behat/symfony2-extension (for integration with Symfony2 web framework)
> behat/behat suggests installing behat/yii-extension (for integration with Yii web framework)
> behat/behat suggests installing behat/mink-extension (for integration with Mink testing framework)

Are these suggestions relevant or?

**Comment by Arul-** [comment]
every component that we use can suggest another component, presenting suggested components use case

This is a `composer` feature

If your work is relevant to the presented use case and you find value, you can go ahead and install them

Else just ignore them!
