### ISSUE TITLE
Downloading the explorer via composer

### ISSUE THREAD

**Issue by lathspell** [Luracast/Restler#603]
Documentation says:

> If you have successfully completed Installation Step 2, you should have Restler API Explorer installed in vendor/Luracast/explorer folder.

This only works when creating a new composer project which generates a composer.json that contains a snippet which fetches "luracast/explorer" as zip file from github...

Wouldn't it be possible to create a composer package that just contains the HTML+Javascript files and can be installed using "composer require luracast/explorer" and then symlinking "vendor/luracast/explorer/htdocs/" to htdocs/explorer/"?

I like to add Restler and its Explorer to an existing project.

**Comment by Arul-** [comment]
This is no longer required as Explorer is now bundled with Restler
