### ISSUE TITLE
Return html from api method (without view)

### ISSUE THREAD

**Issue by JoyceBabu** [Luracast/Restler#605]
Is it possible to return HTML directly from the Api method without using views?

**Comment by Arul-** [comment]
Yes!

Are you using RC5 or RC6? I can provide the code depending on that

**Comment by JoyceBabu** [comment]
Thank you @Arul- 

I have managed to do it by creating a new format `TextHtmlFormat` as defined in 
https://github.com/Luracast/Restler/issues/604
