### ISSUE TITLE
Support for RFC 7807 API Problem

### ISSUE THREAD

**Issue by lathspell** [Luracast/Restler#606]
I like all my REST services return errors in the same data structure, namely the "Problem Details for HTTP APIs" format speciifed in https://tools.ietf.org/html/rfc7807.

That requires a custom error formatter/handler. Currently custom error handlers are not well supported as addErrorHandler() requires a class which has functions called handle500() and similar but does not support a generic handleException().

Please support RFC 7807 by allowing a handleAll() method in Restler::message() and maybe even provide a \Luracast\Restler\ApiProblemErrorHandler out of the box.

**Comment by Arul-** [comment]
Setting `Defaults::$composeClass` to custom class is the recommended approach. If you can make it generic make a pull request to add that class to Restler repository to help others

We had the plan to add many composer classes for different standards to make it easy for developers
