### ISSUE TITLE
Composer Restler/Framework or Luracast/Restler?

### ISSUE THREAD

**Issue by RVN-BR** [Luracast/Restler#609]
Out of curiosity, is one over the other recommended/more up to date?

Can I tag a specific version as "stable/latest" for production instead of "dev-master#dea5b92"?  Also, would there be any reason that tagging only "dev-master" would be different than "dev-master#dea5b92"? (seems like that is the latest commit??)

I tried using

    "luracast/restler":"dev-master#dea5b92",

Which works,

    "restler/framework":"dev-master#dea5b92",
Also works (but no explorer)

    "restler/framework":"dev-master#dea5b92",
    "luracast/explorer":"dev-master", <--- package doesnt exist error (despite being listed on packagist as a required-dev?

I also tried using restler/framework twice with a tag dev-features/explorer but composer doesnt bring the same package 2 times even if it is a different tag...

EDIT: 
    "restler/framework":"dev-master#dea5b92",
Works WITH explorer, despite running composer with no-dev... go figure... So the question is is there any difference in running luracast/restler or restler/framework? and any idea about the last commit and no commit having strange results?

Thanks for shining a light on this!

**Comment by Arul-** [comment]
Both are the same mostly, `restler/framework` contains only the source code no tests etc so it will be lite
I run a script to extract it from the `luracast/restler` when I push updates.

**Comment by Arul-** [comment]
It is a complete rewrite for compatibility. nothing documented yet

but clone and take a look at the public folder

**Comment by Arul-** [comment]
after `composer install` you can run `php public/index_*.php`

**Comment by Arul-** [comment]
`api/examples` folder will look familiar

**Comment by RVN-BR** [comment]
Cool! 👍 will do!
