### ISSUE TITLE
PHP has reserved all method names with a double underscore prefix for future use

### ISSUE THREAD

**Issue by gnouet** [Luracast/Restler#613]
Hi, 

PHP has reserved all method names with a double underscore prefix for future use.
There is five methods impacted : 

- __isAuthenticated
- __toArray
- __getMaximumSupportedVersion
- __isAllowed
- __getWWWAuthentificationString

If we rename all method to remove double underscore, it will introduce breaking change. But as it impacts interfaces, I do not see any good solution.

Is this a change that can be considered?
I did a little test that could become a merge request.

**Comment by gnouet** [comment]
I created a PR in this sense. https://github.com/Luracast/Restler/pull/616 
Thanks for your feedback !

**Comment by Arul-** [comment]
Restler 4, and 5 (formally RC5 and RC^) won't have this change. Only restler 6 will have it
