### ISSUE TITLE
Does Reslter need a new maintainer?

### ISSUE THREAD

**Issue by vladimino** [Luracast/Restler#617]
It seems that @Arul-  stepped down from maintaining this very highly popular library. It's pitty but we all have own reasons and obstacles. I'm using Restler in a couple of production applications and would like to see its growth driven by OS community, hence, volunteering to help with maintenance of this project. 

Quick self-introduction: I'm a senior PHP developer with 15+ years of experience. Currently, I live in Berlin. In 2019 I decided that it's time for me to give back to the community more than ever before, so I'd be glad to focus my efforts on something I personally use and love.

Let me know what you all think on the subject.

Cheers,
Vlad

**Comment by Arul-** [comment]
@vladimino Thanks for your interest and you are welcome to volunteer :)

However, I did **not** step down :) In fact, I'm actively developing a brand new version of restler 

https://github.com/Arul-/reactive-restler/tree/dev

I want to get it functional, and then publish it as Restler 4.0 here! 

Let me know, how you want to help. Also in terms of Restler 3 list down the pressing maintenance issues as a user.

**Comment by Arul-** [comment]
Send me an email to arul@luracast.com with ways to reach you on a chat, I will continue there

**Comment by Arul-** [comment]
I'm still waiting for you!

**Comment by vladimino** [comment]
We've caught up on Facebook. I guess, this issue can be closed. Thanks for your openness and will be glad to contribute in any way! 👍
