### ISSUE TITLE
json_decode in JsonFormat.php

### ISSUE THREAD

**Issue by artzaik** [Luracast/Restler#621]
json_decode PHP function has 4 parameters

`json_decode ( string $json [, bool $assoc = FALSE [, int $depth = 512 [, int $options = 0 ]]] ) : mixed`

But in JsonFormat.php you use json_decode with 2 parameters:
`$decoded = json_decode($data, $options);`

$options parameter is the 4th parameter, but you use like second parameter. When $options=0 we get a object, and with $options > 0 we get a associative array (and not the object we expect).

another question: Why decode function return Obj::toArray($decoded);? Why don't you use json_decode($data, true) to get an associative array?

Regards

**Comment by Arul-** [comment]
@artzaik Thanks for all the input. It was an oversight

All your suggestions are valid and accepted as you can see in the above commit!
