### ISSUE TITLE
PUT without body fails

### ISSUE THREAD

**Issue by RolandRosenfeld** [Luracast/Restler#622]
I defined a function like this:
```php
   /**
    * Unlock user
    *
    *  comment
    *
    * @url PUT {username}/unlock
    * @param string $username {@from path} Username
    */
   public function unlock($username)
   {
      ...
   }
```
Which takes exactly one parameter, that is transported in the URL.

On an old server (with an ancient PHP version) this was usable by
```
curl  -X PUT 'https://soap/usermanage/myusername/unlock'
```
After an upgrade to a newer server with PHP 7 this fails with `400 Bad Request: Error parsing JSON, malformed JSON` 
and I have to send a body with this call like
```
curl  -X PUT 'https://soap/usermanage/myusername/unlock' -d ''
```
or
```
curl  -X PUT 'https://soap/usermanage/myusername/unlock' -H "Content-Type: application/json" -d '{}'
```

Also explorer/swagger fails on this PUT function with only one parameter in the path, because it doesn't allow me to enter a body but runs into the `400 Bad Request: Error parsing JSON, malformed JSON` error.

A different PUT function with a second parameter, that is sent via POST works without problems:
```php
   /*
    * @url PUT pw/{username}
    * @param string $username Username
    * @param string $newpw {@from body} new password, which should be set
```
since it always uses a non empty POST body.

Any idea how to work around this on the restler side? Currently we have to modify all our clients to send an empty `{}` JSON body on the unlock requests.

**Comment by nicodeboer76** [comment]
I have fixed this by changing this line in Restler.php file on line 561:

            if ($stream === FALSE || stream_get_contents($stream) === '')
                return array();

PHP 7.x has changed the behaviour of json_decode. 
See: https://bugs.php.net/bug.php?id=71718

**Comment by Arul-** [comment]
This is now working fine with the latest changes to restler 5!
