### ISSUE TITLE
Timeline for Restlers future

### ISSUE THREAD

**Issue by davidsneighbour** [Luracast/Restler#632]
Hello, are there any plans to release version 3 into the wild and cleanup and extend the documentation? I am working with Restler since the very early days and find it sad how it slowed down just an inch before the finish line. The README talks about PHP5.2 which is dead for years now :(

I propose to have an honest lookout with a timeline so users can decide if they learn another framework or stay on board.

Also, have a look at the [stale bot](https://github.com/marketplace/stale) which can help with managing old issues that might be "stale". Auto closing included.

**Comment by Arul-** [comment]
Thanks for your interest in Restler, lm working on version 4 of restler with lot of exciting features. Check it out at  https://github.com/Arul-/reactive-restler It will soon be released officially here

**Comment by roynasser** [comment]
Hi Arul, have you (or anyone) been running this at all in production?  I dont have any experience with reactphp so i'm interested in how it works in the wild...

Currently we have about 80-150rps.

**Comment by Arul-** [comment]
@roynasser Yes, we have successfully run production apps on Restler 4 and swoole
