### ISSUE TITLE
Restler::__construct( ..., $refreshCache ) does not work as advertised

### ISSUE THREAD

**Issue by richardpickett** [Luracast/Restler#636]
Documentation/comment has:

`     * @param bool    $refreshCache      will update the cache when set to true`

This is inaccurate.  You have to set both `$productionMode` and `$refreshCache` to true in order to update the cache, which is counter-productive.

You'd want the cache to be built in non-production, so in production it can save time by loading the already-generated cache.

**Comment by Arul-** [comment]
You are right, it is currently used mainly to test the production mode and look at the generated cache

we have to update the documentation to reflect that cache is created only in production mode and it will be refreshed only when `$refreshCache` is set to `true`

Ideally, we need to use it to check if source files are updated and turn on `$refreshCache` only for one request so that we serve updated api

**Comment by richardpickett** [comment]
Thanks for the clarifcation, @Arul- .

For it's current state, what's the correct way to get it to rebuild the entire cache?  if I pass $production = true and $refreshCache = true, and then addAPIClass() and setOverridingFormats() on my classes and formats, is that good enough, or do I actually have to handle() requests?

I'm asking because I can write a "cache building" script that fires up as part of my build pipeline, so the artifact that's deployed can _not_ build the cache, but used the pre-built cache.

Thanks again!

**Comment by Arul-** [comment]
Here is what I think

production mode should be always set to true on the production server

Your deployment pipeline can create a temp file every time a deployment is done. let's call it `_updated` (with no expansion) on the project root

Your index.php can have the following logic

```php
<?php

$refreshCache = false;

if(file_exists(BASE . '/_updated')){
    $refresgCache = true;
    unlink(BASE . '/_updated')
}

$restler = new Restler(true, $refreshCache);

//...
```

Your cache will be refreshed every time you push an update to the server. In a simple setup, it can be a GIT PUSH hook that creates this file. Any continuos integration tool can easily do this

HTH,
Arul
