### ISSUE TITLE
Validator.php and arrays

### ISSUE THREAD

**Issue by eduh** [Luracast/Restler#638]
Struggling to get restler 2.0 to replace with restler 3.0.0 rc5 
We have a simple put method to update a record and we send a arrays like this as a simple example
    [0] => MNT0000070
    [1] => MNT0000084
    [2] => MNT0000085
    [3] => MNT0000086
Now response is 
    <error>
        <code>400</code>
        <message>Bad Request: Invalid value specified for `value`. Expecting alpha numeric value</message>
    </error>
    <debug>
        <source>Validator.php:625 at validate stage</source>
        <stages>
            <success>get</success>
            <success>route</success>
            <success>negotiate</success>
            <failure>validate</failure>
            <failure>message</failure>
        </stages>
    </debug>

When I add some extra logging in the validator it fails around 474 where i detect that the $input is my array but then the code fails at line 472 where the error is raised.
                case 'string' :
                    if (!is_string($input)) {
                        if ($info->fix) {
                            $input = strval($input);
                        } else {
                            $error .= '. Expecting alpha numeric value';
                            break;
                        }
                    }

Am I doing something wrong or is this is a bug?

**Comment by eduh** [comment]
or is it possible to disable the validator for I use my own validation libs

**Comment by Arul-** [comment]
You can try disabling auto validation by

https://github.com/Luracast/Restler/blob/master/vendor/Luracast/Restler/Defaults.php#L133

```php
use Luracast\Restler\Defaults;

Defaults:: autoValidationEnabled = false;
```

**Comment by Arul-** [comment]
If you can provide a simplified example API to reproduce the problem, we can try and come up with more solutions!

**Comment by eduh** [comment]
Thank you, disabling the validation did the trick for me. Having a further look the problem also might have been caused by a PHPDOC declarations where the type 'mixed' was omitted. Anyway, thanks for the tip.

**Comment by mrsolarius** [comment]
Have you found anything about that?
In the last version of Restler this error still here.
I have the same problem with this example from the documentation : 
```php
/**
* Array of authors
*
* @param array $authors {@type Author}
*
* @return array {@type Author}
*/
function postAuthors(array $authors)
{
		return $authors;
}

class Author
{
    /**
     * @var string {@from body} {@min 3}{@max 100}
     * name of the Author {@required true}
     */
    public $name = 'Name';
    /**
     * @var string {@type email} {@from body} {@required false}
     * email id of the Author
     */
    public $email = 'name@domain.com';
}
```

Here with a request like that : 
```json
[
  {
    "name": "My Name",
    "email": "my.name@me.biz"
  },
 {
    "name": "Jean Pierre",
    "email": "jean.pierre@mail.fr"
  }
]
````

I get this error : 
```json
{
  "error": {
    "code": 400,
    "message": "Bad Request: Invalid value specified for `authors[0]`"
  },
  "debug": {
    "source": "Validator.php:718 at validate stage",
    "stages": {
      "success": [
        "get",
        "route",
        "negotiate",
        "authenticate"
      ],
      "failure": [
        "validate",
        "message"
      ]
    }
  }
}
```

**Comment by eduh** [comment]
We disabled the validator as indicated above so we have solved it for our situation. But if you use it make 100% sure that the postdata is correct according to your phpdoc definitions...although there seems nothing wrong with your example as far as I can see. Sorry I can't help for this one.

**Comment by mrsolarius** [comment]
Too bad. Do you think that I need to open an issue for this particular problem?

**Comment by eduh** [comment]
think that is the best way to do it, Good luck.

**Comment by Arul-** [comment]
@mrsolarius yours is a perfectly valid use-case. It is already part of the tests. You can see

1. The class in https://github.com/Luracast/Restler/blob/e82d5622f5a1798c3c208867184a469fb4fd445c/public/tests/param/Type.php#L133
2. Test is in https://github.com/Luracast/Restler/blob/e82d5622f5a1798c3c208867184a469fb4fd445c/features/tests/param/type.feature#L345

I just ran all tests and confirm that this feature is working fine!

If you can provide an example that fails, we can look at it further!

**Comment by mrsolarius** [comment]
I have tested with the implementation of Restler in Dolibarr v12 that could come from here 🤔 .
I have test with only Restler and it works.

**Comment by Arul-** [comment]
@mrsolarius thanks for letting us know! not sure why it does not work with Dolibarr

**Comment by Arul-** [comment]
@mfonsatti you either add the fully qualified path in the comments or add an import statement in PHP as shown below

```php
<?PHP

use fully\qualified\path\Author;

//...
```
and then use just  `{@type Author}`

Both are supported. otherwise, it will look for Author without a namespace or namespace of the controller and fail

**Comment by mfonsatti** [comment]
yes, I always prefer and use always the import way... 
I thought that suggesting the fully qualified was the best way to explain that at some point the framework needs to now how to load the class ... ;-)
