### ISSUE TITLE
Question - swagger 2.0 generated spec

### ISSUE THREAD

**Issue by shayaantx** [Luracast/Restler#641]
Hi,

Using latest restler (3.1.1), I added Explorer (which should be swagger 2.0 based on Scope.php) as an api class and the resources.json generated is still 1.1 (confirmed this by running the generated json via the swagger io validator). Is this expected or am I missing something?

```
$this->addAPIClass('Luracast\\Restler\\Resources');
$this->addAPIClass('Explorer');
```

I break-pointed inside every method in explorer and none are called during generation of resources.json, am I missing something obvious to turn on swagger 2.0 specification?

When I look at the resources.json it shows this snippet for Explorer class, which seems weird unless I'm misunderstand how this class is used to generate swagger 2.0 json files.

```
{
    "apiVersion": "2",
    "swaggerVersion": "1.1",
    "basePath": "<redacted-hostname>",
    "produces": [
        "application/json"
    ],
    "consumes": [
        "application/json"
    ],
    "apis": [
        {
            "path": "/v2/resources/explorer-v2",
            "description": "Class Explorer"
        },
...
```

Thanks

**Comment by Arul-** [comment]
$this->addAPIClass('Luracast\\Restler\\Resources');

above is an old version and not recommended.

as you can see in https://github.com/Luracast/Restler/tree/3.1.1/vendor/Luracast/Restler/Explorer there are two versions of explorer classes supporting different swagger spec

    $this->addAPIClass('Explorer2');

This works because of an alias set in Scope class

**Comment by shayaantx** [comment]
I guess I don't see how resources.json gets generated in the source without that original mapping. If I remove "Luracast\\Restler\\Resources" mapping I'll just get a route mapping error. using explorer vs explorer2 makes no difference since they are both mapped to same thing.

**Comment by Arul-** [comment]
there is no resources path anymore! just point to `/explorer2` if you use

    $this->addAPIClass('Explorer2');

the spec will be available from `/explorer2/swagger.json`

    $this->addAPIClass('Explorer2', 'explorer');

will make it available in `explorer/swagger.json`
swagger

**Comment by shayaantx** [comment]
now I see it/understand thanks for the help!

**Comment by Arul-** [comment]
you are welcome
