### ISSUE TITLE
update luracast/restler to Open API Specification 3.0

### ISSUE THREAD

**Issue by codechop** [Luracast/Restler#642]
I am Integrating [Redoc](https://github.com/Redocly/redoc) into luracast restler and remove existing swagger.
I have used the Redoc documentation which further throw an error: 
> 
> Document must be valid OpenAPI 3.0.0 definition
> 
I have tried this in explorer/index.html, assuming that "../resources.json" in <redoc> tag which is created by Restler will get to Redoc. 

```
<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <!--
    ReDoc doesn't change outer page styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='../resources.json'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
  </body>
</html>
```

@Arul-  How can I upgrade Restler  to OpenAPI 3.0.

Here is error screenshot: https://prnt.sc/w7qxip

**Comment by Arul-** [comment]
We have integrated Redoc and Swagger 3 spec in a new version of restler available from https://github.com/Arul-/reactive-restler/tree/6.3.0/src/OpenApi3 we will soon bring it up here!

You may contribute by backporting it to Restler 3
