### ISSUE TITLE
Usage of @from head

### ISSUE THREAD

**Issue by kaizirlewagen** [Luracast/Restler#645]
It is possible to move params from query to header?

We try {@from head} but explorer shows already the param in the query or url and not in the http header.

Do you have an idea?

**Comment by Arul-** [comment]
Restler 3 does not have that feature built in. You can manually read from headers in your API method

**Comment by kaizirlewagen** [comment]
Thank you for the fast response.

Do you have a small sample for it?

**Comment by Arul-** [comment]
See https://www.geeksforgeeks.org/how-to-read-any-request-header-in-php/

**Comment by kaizirlewagen** [comment]
Thx. I will give a try.

**Comment by kaizirlewagen** [comment]
I modify "Explorer.php"

```
private function securityDefinitions()
    {
        $r = new stdClass();
        $r->api_key = (object)array(
            'type' => 'apiKey',
            'name' => 'api_key',
            //'in'   => 'query',
            'in'   => 'header',
        );

        return $r;
    }
```

So the api_key will be moved to the header, after the my "AccessControl.php" must contain this code to get the api_key from the header.

```
        foreach (getallheaders() as $name => $value) { 
        	if(strcmp($name, 'api_key') == 0) {
        		$api_key = $value;
        		
        	}
        }  
```

**Comment by Arul-** [comment]
Newer version of restler https://github.com/Arul-/reactive-restler has better explorer support with open API 3 specification

**Comment by kaizirlewagen** [comment]
I have a working version with version 5. But...

if i use this in my api class (get or delete):

`* @param string $token {@from header} {@required false} (required)`

All works fine through explorer. The parameter type is set to "header".

![Screenshot (524)](https://user-images.githubusercontent.com/8393808/124098032-72a20800-da5c-11eb-9cc2-29e8aac38750.png)

But if i use the @url param in my class function

`* @url GET what/ever/you/want`

the explorer does a replace from header to query but only in GET and DELETE functions. In POST, PUT all works fine.

![Screenshot (525)](https://user-images.githubusercontent.com/8393808/124098349-c6145600-da5c-11eb-826a-561f3c5ab200.png)

Do you have an idea where my error is?

**Comment by kaizirlewagen** [comment]
See Routes.php Line 269

`$copy['metadata']['param'][$i][$dataName]['from'] = 'query';`

The type will be overwriten.

**Comment by Arul-** [comment]
Will fix it and update you!

**Comment by Arul-** [comment]
Pushed the fix in 5.0.5 (536f349199f0b785b6b96b629b84f2d907dc284e)please check and let me know

**Comment by kaizirlewagen** [comment]
Thx for the fix. I tested it but the param will be overwriten with query. The fix does not work.

``                        
} elseif (isset($p['from']) && 'header' === $p['from']) {
  continue;
 } elseif ($httpMethod === 'GET' || $httpMethod === 'DELETE') {
  $copy['metadata']['param'][$i][$dataName]['from'] = 'query';
}
`

the elseif ($httpMethod === 'GET' || $httpMethod === 'DELETE') { matches for each GET or DELETE call. So in this elseif the test for the header must be implemented here.

`
                        } elseif ($httpMethod === 'GET' || $httpMethod === 'DELETE') {
                            if ($copy['metadata']['param'][$i][$dataName]['from'] === 'header')
                            {
                            	// do nothing
                            } else {
                                $copy['metadata']['param'][$i][$dataName]['from'] = 'query';
                            }
`

**Comment by Arul-** [comment]
noted!

**Comment by Arul-** [comment]
Fixed now in  5.0.5 (c7794d7c9157af450e886bcd8bcafe227ffb6842) please check and let me know

**Comment by Arul-** [comment]
@kaizirlewagen did you manage to check?

**Comment by kaizirlewagen** [comment]
@Arul- sorry for the late answer. Yes, i checked the patch and it works. Thx for your work.
