### ISSUE TITLE
Default Format

### ISSUE THREAD

**Issue by abides** [Luracast/Restler#646]
Using 3.1.0

`$r->setSupportedFormats('JsonFormat','TextPlainFormat','XmlFormat');`

This should set the default format JsonFormat. In documentation : "First format specified in Restler::setSupportedFormats is used as the default format when client does not specify the format."

But when i add XmlFormat in setSupportedFormats its always return xml results as default. .json or .txt working without any problem. I want to return json as default when i do no specify the format on calls.

**Comment by Arul-** [comment]
This is because you are trying in the browser and it is sending XML as one of the formats it accepts using the Accepts header. Just try the same request through curl you will see default being used
