### ISSUE TITLE
Is there an ~easy~ way to return custom binary files in specific methods?

### ISSUE THREAD

**Issue by igorsantos07** [Luracast/Restler#648]
My API is JSON-only, except for some very specific cases: some methods would return images or PDFs - but would still throw JSON errors in case something goes awry. Even then, requests are still made in JSON (if needed).

What's the best way to do this? Would I need to code a full-blown Format class and override the format in each of those methods? The MultiFormat example covers text formats but there's no hint on how to handle binary formats like these.

Example:
- GET /user/avatar: default call; returns a PNG base64, suitable for further processing in the frontend
- GET /user/avatar.png: returns the actual PNG image
- GET /user/avatar.jpg: returns A JPG version, for non-transparent uses
- GET /user: user details in JSON
- GET /user.pdf: a printable summary about the user (internally generated, of course I don't expect Restler to format the PDF for me haha)

----------
EDIT: I wonder if this could be achievable from a new method in the PassThrough class? (missing docs!) We could pass the content, the extension/mime, and it would pass the content, skipping all the formatting class fuss.

**Comment by Arul-** [comment]
This can be already done using the `PassThrough` class.  Take a look at https://github.com/Luracast/Restler/blob/f760e3434008bdc1df61540cfe8c3710febf38cb/src/Explorer/v1/Explorer.php#L139-L174

using conditional statements, we are able to load HTML, images, js files etc
