### ISSUE TITLE
@example doesn't seem to be respected?

### ISSUE THREAD

**Issue by igorsantos07** [Luracast/Restler#649]
I'm not sure if I got the `@example` tag correctly, but isn't it supposed to show `account: "test"`?

![image](https://user-images.githubusercontent.com/532299/114340823-ccb2c180-9b2e-11eb-9a1d-b0fd83ee10df.png)
![image](https://user-images.githubusercontent.com/532299/114340858-dccaa100-9b2e-11eb-9533-93286430626a.png)

**Comment by Arul-** [comment]
@example support is not present in 3.0 RC6 and 5.0 (new semantic version for RC6) If you need that you can use 4.0 instead (formally 3.0 RC5)
