### ISSUE TITLE
CommentParse::$allowsArrayValue no longer exists

### ISSUE THREAD

**Issue by DavidCasillasRivero** [Luracast/Restler#652]
[This issue](https://github.com/Luracast/Restler/issues/400) references the use of the `CommentParse::$allowsArrayValue` attribute, but it seems it is no longer available. It is in [label  `3.1.1`](https://github.com/Luracast/Restler/blob/3.1.1/vendor/Luracast/Restler/CommentParser.php), but then it is no longer found. I can not see anything in Changelog either. 

**Is this feature removed?**

**Is there an alternate method of getting the functionallity?**

I'm using it to convert comma separated doc type annotations into arrays. The annotations are used to be able to fine tune the authentication process with information defined in each API method doc type annotation.

**Comment by Arul-** [comment]
It works fine. Correct example is given below

```php
<?php
require __DIR__.'/../vendor/autoload.php';
use Luracast\Restler\Restler;
use Luracast\Restler\CommentParser;

CommentParser::$allowsArrayValue['apiType'] = true;

class Test{
    public $apiType;
    /**
     *@class Test {@apiType parameter_one,parameter_two}
     */
    function index(){
        return $this->apiType;
    }
}

$r = new Restler();
$r->addApiClass('Test');
$r->handle();
```

it gives me the expected result!

```json
[
    "parameter_one",
    "parameter_two"
]
```

I tried it with Restler `4.0.0` (formally `3.0 RC5`) `3.1.0`, and `3.1.1`


Attaching the project here for you to try. unzip and run `composer install`

[ArrayParseExample.zip](https://github.com/Luracast/Restler/files/6508192/ArrayParseExample.zip)
