### ISSUE TITLE
What happened to v4?

### ISSUE THREAD

**Issue by JoyceBabu** [Luracast/Restler#655]
I just noticed that v5 was released when running `composer outdated` and wondered how I missed `v4`. I checked the releases page and found that v4 was released only 3 weeks ago.

Is there any huge change between v4 and v5 requiring a major version bump? v4 is not even mentioned in Changelog on the project's README.

Also, is it safe to upgrade from v3 to v5?

**Comment by Arul-** [comment]
if you are using v3 RC5 you can safely switch to v4. No code changes required

If you are using v3 RC6 you can safely switch to v5

In order to switch to proper versioning and maintenance, we have decided to move forward this way!

The readme is also showing the same
