### ISSUE TITLE
choice problem with validation

### ISSUE THREAD

**Issue by kaizirlewagen** [Luracast/Restler#657]
I am using version 5.0.5

If i use a choice like this:
```
* @param int $loglevel {@from query} Log level (0 = INFO, 1 = DEBUG) {@choice 0,1} {@required false}
```
I get the following error:
```
  "error": {
    "code": 400,
    "message": "Bad Request: Invalid value specified for `loglevel`. Expecting integer value"
  },
  "debug": {
    "source": "Validator.php:718 at validate stage",
```
Only if i select 0 (zero) through the choice. All other integer values are possible only 0 does not work. I need 0 (zero). If i use the empty value, this will be interpreted as 0 (zero).

How can i fix this?

**Comment by richardeaxon** [comment]
I think https://github.com/Luracast/Restler/issues/659 is related and probably has todo with this commit https://github.com/Luracast/Restler/commit/c115e237129d611413b5658f469e61382a383d88.

**Comment by kaizirlewagen** [comment]
In version 5 the file ValidationInfo.php does not have the === "problem".

```
    public static function numericValue($value)
    {
        return ( int )$value === $value
            ? ( int )$value
            : floatval($value);
    }
```
So, the choice problem does already exist. 

The error occurres in Validator.php line 517.

```
            switch ($info->type) {
                case 'int' :
                case 'float' :
                case 'number' :
                    if (!is_numeric($input)) {
                        $error .= '. Expecting '
                            . ($info->type === 'int' ? 'integer' : 'numeric')
                            . ' value';
                        break;
                    }
```

**Comment by Arul-** [comment]
Hope 32da73cd63334e306fa04327f67ad4748040170d in v5 branch fixes this. Can you check?

**Comment by kaizirlewagen** [comment]
@Arul- works perfect. Thx for your work !!!
