### ISSUE TITLE
How to describe response type

### ISSUE THREAD

**Issue by camlafit** [Luracast/Restler#658]
Hello

Sorry to open about this but I've not found information code source and official documentation. How could we provide a response description more accurate ?

By default Explorer display a simple model schema 
```
[ "string" ]
```
![Capture d’écran de 2021-07-08 15-38-07](https://user-images.githubusercontent.com/209915/124931534-9805b780-e002-11eb-839c-b9a048293c3a.png)

We can improve this result if we type phpdoc return 
```
    /**
     * @return array {@type int}
     * /
    public function get($id) {}
```
![Capture d’écran de 2021-07-08 15-39-34](https://user-images.githubusercontent.com/209915/124931652-b8ce0d00-e002-11eb-89f8-7441519df4f3.png)

if we set any other value than ```array``` as ```int``` or ```string```, model schema is removed
if we set some value in ```{@type }``` it's broken also as ```Object``` , ```array```

How can provide a more accurate description about as we can get with ```{@params}``` description ?

As :
![Capture d’écran de 2021-07-08 15-43-55](https://user-images.githubusercontent.com/209915/124932401-575a6e00-e003-11eb-9d04-64a19ad5d1c3.png)

Thanks a lot

**Comment by camlafit** [comment]
related to #565

**Comment by camlafit** [comment]
Note, following https://github.com/Luracast/Restler/blob/master/src/Explorer/v2/Explorer.php#L457, some {@type} could be provided. Following code, we could set 
* ```@return array Description {@type associative}```
* ```@return array Description {@type indexed}```
* ```@return array Description {@type AnyObject}```
* ```@return antype Description```

With  ```{@type indexed}``` return it's forced to ```string```
If ```array``` is not set or different, in this case it's forced to ```string```

**Comment by Arul-** [comment]
Check this with the latest commits in the V5 branch. Hope its resolved

**Comment by Arul-** [comment]
now available in 5.0.7

**Comment by camlafit** [comment]
Hello

This use case broke again : 
```
@return array qezaezaezaezza {@type array}
```
Thanks

**Comment by Arul-** [comment]
That use case is not supported by swagger. You can do one of the following instead

1.  `@return array description {@type indexed}` indexed array
2. `@return array description {@type associative}` associative array / object
3. `@return object[] description` array of objects
4. `@return string[] description` array of strings
