### ISSUE TITLE
@throttle error, does it require ratelimit or something?

### ISSUE THREAD

**Issue by abides** [Luracast/Restler#663]
Hello,

```
/**
 * Home Index
 *
 * @throttle 200
 *
 */
public function index()
{
	return $this->init;
}
```

Its actually working and delay request for 200ms but gives an error;

`{"error":{"code":500,"errno":8,"message":"Undefined index: throttle","file":"\/var\/www\/tarama\/vendor\/restler\/framework\/Defaults.php","line":357}}`

Does it require something else?

**Comment by Arul-** [comment]
What is the version of restler you are using? We tried with Restler 5, it works fine

**Comment by abides** [comment]
"restler/framework": "5.0.8"

Have php 7.4.18 also have fatal error handler and error_reporting(E_ALL); on development mode to see all kind of problematic stuff. Probably this trigger notice or something?

**Comment by Arul-** [comment]
Can you try changing Line 357 of Defaults.php to the following

    if (isset(Defaults::$validation[$name]) && is_array(Defaults::$validation[$name])) {

And then see if the error disappears

I could not reproduce the error so, need to fix it on yours. I tried with the following code
[throttle.zip](https://github.com/Luracast/Restler/files/6996580/throttle.zip)

**Comment by abides** [comment]
Error (notice) dissapear with that. I'm against to make changes on the vendor code to fix something since its come back with first update. Can you change the master too if this change does not affect anything else?

Thank you, best regards.

**Comment by Arul-** [comment]
Done!
