### ISSUE TITLE
Error on tag naming Restler/Framework

### ISSUE THREAD

**Issue by camlafit** [Luracast/Restler#666]
Hello

I've seen a typo on tag naming on https://github.com/Luracast/Restler-Framework/tags 
5.07 and 5.08 are published and are greater than 5.0.9

I think should be better to delete these tags and recreate them correctly.

Thanks

**Comment by camlafit** [comment]
As temporary workaround, on composer.json
We can do 
```
        "restler/framework": "5.0.9",
```
and do a ```composer update``` should do 
```
  - Downgrading restler/framework (5.08 => 5.0.9)
```

**Comment by Arul-** [comment]
Thanks for letting us know, it is fixed now!

**Comment by camlafit** [comment]
thanks a lot
