### ISSUE TITLE
XmlFormat encoding problem

### ISSUE THREAD

**Issue by mfonsatti** [Luracast/Restler#676]
Restler V3.0.0

I'm trying to create an API that wraps a CURL to another API that returns an XML string.
I would get that string and return it as XML using Restler XmlFormat.

No extension .xml in the URL.

API annotation
@format XmlFormat

The problem is that after the encode execution by the XmlFormat the result is that every < or > is changed to &lt &gt

How can I solve this?

**Comment by Arul-** [comment]
Can you give us an example code to show how you are using it?

**Comment by mfonsatti** [comment]
Below is a snippet that summarizes the steps

`class SearchApiProxy
{
    /**
     * @url POST /
     * @access protected
     * @format XmlFormat
     */
    public function searchApiProxy() 
    {
            // get the XML string  from an internal API
            $xmlString = $this->searchApiCurl();
            $temp_xml = new DOMDocument();
            $temp_xml->loadXML($xmlString);
            // $xmlString contains also <?xml version="1.0" encoding="UTF-8"?>, that will be added by restler, so I remove it
            $xml = $temp_xml->saveXML($temp_xml->documentElement);
            return $xml;
    }
...
`

Calling the API with postman this is the result
![image](https://user-images.githubusercontent.com/6352972/153841134-70df1f17-b81e-4d68-9a2e-f3eb1f1ef39f.png)

**Comment by Arul-** [comment]
You already have XML coming from another server. you want to serve unaltered.
Since you  are encoding the XML string as XML again this happens

let me give you some sample code to directly send the XML instead

**Comment by mfonsatti** [comment]
The server that provides the XML as a string cannot be changed, that's why I tried the way of new DOMDocument().

**Comment by Arul-** [comment]
instead of restler handling the response, you handle it directly in this case

Below is an example

```php
<?php
{
    /**
     * @url POST /
     * @access protected
     * @format XmlFormat
     */
    public function searchApiProxy() 
    {
            // get the XML string  from an internal API
            $xmlString = $this->searchApiCurl();
            header('Content-Type: text/xml'); // add more headers as needed
            die($xmlString);
    }
```

**Comment by mfonsatti** [comment]
I did something similar in one of my test, but instead of the die() I just used the echo ... anyway thanks for the suggestion ;-)

**Comment by Arul-** [comment]
Close once you test and find it working!

**Comment by Arul-** [comment]
Let me close it now! You can reopen if needed later
