### ISSUE TITLE
Wrong variable self::$encoderFunctionName instead of self::$stringEncoderFunction used

### ISSUE THREAD

**Issue by DirkGerigk** [Luracast/Restler#695]
Hi,

https://github.com/Luracast/Restler/blob/dde49c566e5bb4266634ef2748c79747134d8c4e/src/Data/Obj.php#L124

should be the same as here

https://github.com/Luracast/Restler/blob/dde49c566e5bb4266634ef2748c79747134d8c4e/src/Data/Obj.php#L89

Also this line is missing an **return**

https://github.com/Luracast/Restler/blob/dde49c566e5bb4266634ef2748c79747134d8c4e/src/Data/Obj.php#L139

**Comment by Arul-** [comment]
Thanks for pointing it out!
