### ISSUE TITLE
Forbidden: Content type multipart/form-data is not supported.

### ISSUE THREAD

**Issue by AfzalivE** [Luracast/Restler#99]
When I try to do a multipart/form-data POST, Restler replies with:

``` json
{
    "error": {
        "code": 403,
        "message": "Forbidden: Content type multipart/form-data is not supported."
    }
}
```

I was under the impression that Restler 3 would have form-data support. Right now, I'm just trying to get some form-data, I saw some format examples for file upload though. Any light on this would help. Thanks! (did a pull some moments ago to confirm)

Congrats on the v3 release!

**Comment by nsarmiento** [comment]
i had the same problem.
but I solve using the atribute name.
               <input type ="file" name ="some">
I used mvc .net

**Comment by Arul-** [comment]
@nsarmiento can you explain a bit more?

**Comment by nsarmiento** [comment]
@Arul-  My code had the problem that when i use this 

                <div class="col-md-8">
                    <input type="file" id="IdInputFile"/>
                </div>

The AcctionResult in mi controller doesn't get the file so i use the atribute "name"

                <div class="col-md-8">
                    <input type="file" id="IdInputFile" name="NameInputFile" />
                </div>

this solve the problem 

Well... Also you need to use this in your controller if you are using mvc

HttpPostedFileBase image = Request.Files["NameInputFile"];
